package com.lowes.entity;

//Generated 16/12/2015 11:32:08 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
* Aid generated by hbm2java
*/
@Entity
@Table(name = "AID")
public class Aid implements java.io.Serializable {

	private static final long serialVersionUID = -3849355370629451630L;
	
	private int idAid;
	private String descripcion; // hasta 100 caracteres
	private String aid; // 5 caracteres
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String numeroDescripcionAid;


	public Aid() {
	}
	
	public Aid(int idAid) {
		this.idAid = idAid;
	}
	
	public Aid(int idAid, String descripcion, String aid) {
		this.idAid = idAid;
		this.descripcion = descripcion;
		this.aid = aid;
	}

	public Aid(int idAid, String descripcion, String aid, short activo, Date creacionFecha, int creacionUsuario) {
		this.idAid = idAid;
		this.descripcion = descripcion;
		this.aid = aid;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public Aid(int idAid, String descripcion, String aid, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario) {
		this.idAid = idAid;
		this.descripcion = descripcion;
		this.aid = aid;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_AID", unique = true, nullable = false)
	public int getIdAid() {
		return this.idAid;
	}

	public void setIdAid(int idAid) {
		this.idAid = idAid;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "AID", nullable = false, length = 5)
	public String getAid() {
		return this.aid;
	}

	public void setAid(String aid) {
		this.aid = aid;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Transient
	public String getNumeroDescripcionAid() {
		numeroDescripcionAid = String.valueOf(this.aid) + " - " + this.descripcion;
		return numeroDescripcionAid;
	}

	public void setNumeroDescripcionAid(String numeroDescripcionAid) {
		this.numeroDescripcionAid = numeroDescripcionAid;
	}
	
	
}