package com.lowes.entity;

//Generated 16/12/2015 11:32:08 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
* AidConfiguracion generated by hbm2java
*/
@Entity
@Table(name = "AID_CONFIGURACION", uniqueConstraints = @UniqueConstraint(columnNames = "ID_AID") )
public class AidConfiguracion implements java.io.Serializable {

	private static final long serialVersionUID = 7544846808290052627L;

	private int idAidConfiguracion;
	private Aid aid;
	private CategoriaMayor categoriaMayor;
	private CategoriaMenor categoriaMenor;
	private Compania compania;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

//	ID's de objetos 
	private int idAid;
	private int idCategoriaMayor;
	private int idCategoriaMenor;
	private int idCompania;
	
	
	public AidConfiguracion() {
	}

	public AidConfiguracion(int idAidConfiguracion, Aid aid, CategoriaMayor categoriaMayor,
			CategoriaMenor categoriaMenor, short activo, Date creacionFecha, int creacionUsuario) {
		this.idAidConfiguracion = idAidConfiguracion;
		this.aid = aid;
		this.categoriaMayor = categoriaMayor;
		this.categoriaMenor = categoriaMenor;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public AidConfiguracion(int idAidConfiguracion, Aid aid, CategoriaMayor categoriaMayor,
			CategoriaMenor categoriaMenor, Compania compania, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario) {
		this.idAidConfiguracion = idAidConfiguracion;
		this.aid = aid;
		this.categoriaMayor = categoriaMayor;
		this.categoriaMenor = categoriaMenor;
		this.compania = compania;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_AID_CONFIGURACION", unique = true, nullable = false)
	public int getIdAidConfiguracion() {
		return this.idAidConfiguracion;
	}

	public void setIdAidConfiguracion(int idAidConfiguracion) {
		this.idAidConfiguracion = idAidConfiguracion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_AID", nullable = false)
	public Aid getAid() {
		return this.aid;
	}

	public void setAid(Aid aid) {
		this.aid = aid;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_CATEGORIA_MAYOR", nullable = false)
	public CategoriaMayor getCategoriaMayor() {
		return this.categoriaMayor;
	}

	public void setCategoriaMayor(CategoriaMayor categoriaMayor) {
		this.categoriaMayor = categoriaMayor;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_CATEGORIA_MENOR", nullable = false)
	public CategoriaMenor getCategoriaMenor() {
		return this.categoriaMenor;
	}

	public void setCategoriaMenor(CategoriaMenor categoriaMenor) {
		this.categoriaMenor = categoriaMenor;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_COMPANIA")
	public Compania getCompania() {
		return this.compania;
	}

	public void setCompania(Compania compania) {
		this.compania = compania;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Transient
	public int getIdAid() {
		return idAid;
	}

	public void setIdAid(int idAid) {
		this.idAid = idAid;
	}

	@Transient
	public int getIdCategoriaMayor() {
		return idCategoriaMayor;
	}

	public void setIdCategoriaMayor(int idCategoriaMayor) {
		this.idCategoriaMayor = idCategoriaMayor;
	}

	@Transient
	public int getIdCategoriaMenor() {
		return idCategoriaMenor;
	}

	public void setIdCategoriaMenor(int idCategoriaMenor) {
		this.idCategoriaMenor = idCategoriaMenor;
	}

	@Transient
	public int getIdCompania() {
		return idCompania;
	}

	public void setIdCompania(int idCompania) {
		this.idCompania = idCompania;
	}

}