package com.lowes.entity;
// Generated 11/01/2016 11:16:58 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * AutorizadorProveedorRiesgo generated by hbm2java
 */
@Entity
@Table(name = "AUTORIZADOR_PROVEEDOR_RIESGO")
public class AutorizadorProveedorRiesgo implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;

	private int idAutorizadorProveedorRiesgo;
	private NivelAutoriza nivelAutoriza;
	private Proveedor proveedor;
	private Usuario usuario;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public AutorizadorProveedorRiesgo() {
	}

	public AutorizadorProveedorRiesgo(int idAutorizadorProveedorRiesgo, NivelAutoriza nivelAutoriza,
			Proveedor proveedor, Usuario usuario, short activo, Date creacionFecha, int creacionUsuario) {
		this.idAutorizadorProveedorRiesgo = idAutorizadorProveedorRiesgo;
		this.nivelAutoriza = nivelAutoriza;
		this.proveedor = proveedor;
		this.usuario = usuario;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public AutorizadorProveedorRiesgo(int idAutorizadorProveedorRiesgo, NivelAutoriza nivelAutoriza,
			Proveedor proveedor, Usuario usuario, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario) {
		this.idAutorizadorProveedorRiesgo = idAutorizadorProveedorRiesgo;
		this.nivelAutoriza = nivelAutoriza;
		this.proveedor = proveedor;
		this.usuario = usuario;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_AUTORIZADOR_PROVEEDOR_RIESGO", unique = true, nullable = false)
	public int getIdAutorizadorProveedorRiesgo() {
		return this.idAutorizadorProveedorRiesgo;
	}

	public void setIdAutorizadorProveedorRiesgo(int idAutorizadorProveedorRiesgo) {
		this.idAutorizadorProveedorRiesgo = idAutorizadorProveedorRiesgo;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_NIVEL_AUTORIZA", nullable = false)
	public NivelAutoriza getNivelAutoriza() {
		return this.nivelAutoriza;
	}

	public void setNivelAutoriza(NivelAutoriza nivelAutoriza) {
		this.nivelAutoriza = nivelAutoriza;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_PROVEEDOR_RIESGO", nullable = false)
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

}
