package com.lowes.entity;
// Generated 23/03/2016 04:07:32 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * ComprobacionDeposito generated by hbm2java
 */
@Entity
@Table(name = "COMPROBACION_DEPOSITO", schema = "LWS584")
public class ComprobacionDeposito implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int idComprobacionDeposito;
	private Solicitud solicitud;
	private String descripcion;
	private String archivo;
	private BigDecimal montoDeposito;
	private String pidCm;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private Date fechaDeposito;


	public ComprobacionDeposito() {
	}

	public ComprobacionDeposito(int idComprobacionDeposito, Solicitud solicitud, String descripcion, String archivo,
			BigDecimal montoDeposito, short activo, Date creacionFecha, int creacionUsuario, Date fechaDeposito) {
		this.idComprobacionDeposito = idComprobacionDeposito;
		this.solicitud = solicitud;
		this.descripcion = descripcion;
		this.archivo = archivo;
		this.montoDeposito = montoDeposito;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.fechaDeposito = fechaDeposito;
	}

	public ComprobacionDeposito(int idComprobacionDeposito, Solicitud solicitud, String descripcion, String archivo,
			BigDecimal montoDeposito, String pidCm, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario, Date fechaDeposito) {
		this.idComprobacionDeposito = idComprobacionDeposito;
		this.solicitud = solicitud;
		this.descripcion = descripcion;
		this.archivo = archivo;
		this.montoDeposito = montoDeposito;
		this.pidCm = pidCm;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.fechaDeposito = fechaDeposito;

	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_COMPROBACION_DEPOSITO", unique = true, nullable = false)
	public int getIdComprobacionDeposito() {
		return this.idComprobacionDeposito;
	}

	public void setIdComprobacionDeposito(int idComprobacionDeposito) {
		this.idComprobacionDeposito = idComprobacionDeposito;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@Column(name = "DESCRIPCION", length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ARCHIVO", nullable = false, length = 100)
	public String getArchivo() {
		return this.archivo;
	}

	public void setArchivo(String archivo) {
		this.archivo = archivo;
	}

	@Column(name = "MONTO_DEPOSITO", nullable = false, precision = 17)
	public BigDecimal getMontoDeposito() {
		return this.montoDeposito;
	}

	public void setMontoDeposito(BigDecimal montoDeposito) {
		this.montoDeposito = montoDeposito;
	}

	@Column(name = "PID_CM", length = 250)
	public String getPidCm() {
		return this.pidCm;
	}

	public void setPidCm(String pidCm) {
		this.pidCm = pidCm;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_DEPOSITO", nullable = false, length = 10)
	public Date getFechaDeposito() {
		return this.fechaDeposito;
	}

	public void setFechaDeposito(Date fechaDeposito) {
		this.fechaDeposito = fechaDeposito;
	}

}
