package com.lowes.entity;
// Generated 23/03/2016 12:31:20 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * ComprobacionAnticipo generated by hbm2java
 */
@Entity
@Table(name = "COMPROBACION_ANTICIPO", schema = "LWS584")
public class ComprobacionAnticipo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idComprobacionAnticipo;
	private Solicitud solicitudByIdSolicitudAnticipo;
	private Solicitud solicitudByIdSolicitudComprobacion;

	public ComprobacionAnticipo() {
	}

	public ComprobacionAnticipo(int idComprobacionAnticipo, Solicitud solicitudByIdSolicitudAnticipo,
			Solicitud solicitudByIdSolicitudComprobacion) {
		this.idComprobacionAnticipo = idComprobacionAnticipo;
		this.solicitudByIdSolicitudAnticipo = solicitudByIdSolicitudAnticipo;
		this.solicitudByIdSolicitudComprobacion = solicitudByIdSolicitudComprobacion;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_COMPROBACION_ANTICIPO", unique = true, nullable = false)
	public int getIdComprobacionAnticipo() {
		return this.idComprobacionAnticipo;
	}

	public void setIdComprobacionAnticipo(int idComprobacionAnticipo) {
		this.idComprobacionAnticipo = idComprobacionAnticipo;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD_ANTICIPO", nullable = false)
	public Solicitud getSolicitudByIdSolicitudAnticipo() {
		return this.solicitudByIdSolicitudAnticipo;
	}

	public void setSolicitudByIdSolicitudAnticipo(Solicitud solicitudByIdSolicitudAnticipo) {
		this.solicitudByIdSolicitudAnticipo = solicitudByIdSolicitudAnticipo;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD_COMPROBACION", nullable = false)
	public Solicitud getSolicitudByIdSolicitudComprobacion() {
		return this.solicitudByIdSolicitudComprobacion;
	}

	public void setSolicitudByIdSolicitudComprobacion(Solicitud solicitudByIdSolicitudComprobacion) {
		this.solicitudByIdSolicitudComprobacion = solicitudByIdSolicitudComprobacion;
	}

}
