package com.lowes.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * CuentaContable generated by hbm2java
 */
@Entity
@Table(name = "CUENTA_CONTABLE")
public class CuentaContable implements java.io.Serializable {

	private static final long serialVersionUID = -8907662728111099802L;
	
	private int idCuentaContable;
	private String descripcion;
	private String numeroCuentaContable;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	
	private String numeroDescripcionCuentaContable;

	public CuentaContable() {
	}
	
	public CuentaContable(int idCuentaContable, String descripcion,String numeroCuentaContable) {
		this.idCuentaContable = idCuentaContable;
		this.descripcion = descripcion;
	}
	
	public CuentaContable(int idCuentaContable) {
		this.idCuentaContable = idCuentaContable;
	}
	

	public CuentaContable(int idCuentaContable, String descripcion, String numeroCuentaContable, short activo,
			Date creacionFecha, int creacionUsuario) {
		this.idCuentaContable = idCuentaContable;
		this.descripcion = descripcion;
		this.numeroCuentaContable = numeroCuentaContable;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public CuentaContable(int idCuentaContable, String descripcion, String numeroCuentaContable, short activo,
			Date creacionFecha, int creacionUsuario, Date modificacionFecha, Integer modificacionUsuario) {
		this.idCuentaContable = idCuentaContable;
		this.descripcion = descripcion;
		this.numeroCuentaContable = numeroCuentaContable;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_CUENTA_CONTABLE", unique = true, nullable = false)
	public int getIdCuentaContable() {
		return this.idCuentaContable;
	}

	public void setIdCuentaContable(int idCuentaContable) {
		this.idCuentaContable = idCuentaContable;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "NUMERO_CUENTA_CONTABLE", nullable = false, length = 6)
	public String getNumeroCuentaContable() {
		return this.numeroCuentaContable;
	}

	public void setNumeroCuentaContable(String numeroCuentaContable) {
		this.numeroCuentaContable = numeroCuentaContable;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

	@Transient
	public String getNumeroDescripcionCuentaContable() {
		numeroDescripcionCuentaContable = this.numeroCuentaContable + " - " + this.descripcion;
		return numeroDescripcionCuentaContable;
	}

	public void setNumeroDescripcionCuentaContable(String numeroDescripcionCuentaContable) {
		this.numeroDescripcionCuentaContable = numeroDescripcionCuentaContable;
	}

	
}