package com.lowes.entity;
// Generated 28/12/2015 05:50:04 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EstadoSolicitud generated by hbm2java
 */
@Entity
@Table(name = "ESTADO_SOLICITUD", schema = "LWS584")
public class EstadoSolicitud implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idEstadoSolicitud;
	private String estadoSolicitud;
	private String colorEstatus;

	public EstadoSolicitud() {
	}
	
	public EstadoSolicitud(int idEstadoSolicitud){
		this.idEstadoSolicitud = idEstadoSolicitud;
	}

	public EstadoSolicitud(int idEstadoSolicitud, String estadoSolicitud,String colorStatus) {
		this.idEstadoSolicitud = idEstadoSolicitud;
		this.estadoSolicitud = estadoSolicitud;
		this.colorEstatus = colorStatus;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_ESTADO_SOLICITUD", unique = true, nullable = false)
	public int getIdEstadoSolicitud() {
		return this.idEstadoSolicitud;
	}

	public void setIdEstadoSolicitud(int idEstadoSolicitud) {
		this.idEstadoSolicitud = idEstadoSolicitud;
	}

	@Column(name = "ESTADO_SOLICITUD", nullable = false, length = 100)
	public String getEstadoSolicitud() {
		return this.estadoSolicitud;
	}

	public void setEstadoSolicitud(String estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}
    
	@Column(name = "COLOR_ESTATUS", length = 15)
	public String getColorEstatus() {
		return colorEstatus;
	}

	public void setColorEstatus(String colorEstatus) {
		this.colorEstatus = colorEstatus;
	}
	
    

}
