package com.lowes.entity;
// Generated 28/12/2015 05:50:04 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.apache.commons.lang3.StringEscapeUtils;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

import com.ctc.wstx.util.StringUtil;

import antlr.StringUtils;

/**
 * FacturaArchivo generated by hbm2java
 */
@Entity
@Table(name = "FACTURA_ARCHIVO", schema = "LWS584")
public class FacturaArchivo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idFacturaArchivo;
	private Factura factura;
	private TipoDocumento tipoDocumento;
	private String descripcion;
	private String archivo;
	private String pidCm;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public FacturaArchivo() {
	}
	
	public FacturaArchivo(int idFacturaArchivo) {
		this.idFacturaArchivo = idFacturaArchivo;
	}


	public FacturaArchivo(int idFacturaArchivo, Factura factura, TipoDocumento tipoDocumento, String descripcion,
			String archivo, short activo, Date creacionFecha, int creacionUsuario) {
		this.idFacturaArchivo = idFacturaArchivo;
		this.factura = factura;
		this.tipoDocumento = tipoDocumento;
		this.descripcion = descripcion;
		this.archivo = archivo;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public FacturaArchivo(int idFacturaArchivo, Factura factura, TipoDocumento tipoDocumento, String descripcion,
			String archivo, String pidCm, short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idFacturaArchivo = idFacturaArchivo;
		this.factura = factura;
		this.tipoDocumento = tipoDocumento;
		this.descripcion = descripcion;
		this.archivo = archivo;
		this.pidCm = pidCm;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_FACTURA_ARCHIVO", unique = true, nullable = false)
	public int getIdFacturaArchivo() {
		return this.idFacturaArchivo;
	}

	public void setIdFacturaArchivo(int idFacturaArchivo) {
		this.idFacturaArchivo = idFacturaArchivo;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_FACTURA", nullable = false)
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_DOCUMENTO", nullable = false)
	public TipoDocumento getTipoDocumento() {
		return this.tipoDocumento;
	}

	public void setTipoDocumento(TipoDocumento tipoDocumento) {
		this.tipoDocumento = tipoDocumento;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ARCHIVO", nullable = false, length = 100)
	public String getArchivo() {
		return this.archivo;
	}

	public void setArchivo(String archivo) {
		this.archivo = archivo;
	}

	@Column(name = "PID_CM", length = 250)
	public String getPidCm() {
		return this.pidCm;
	}

	public void setPidCm(String pidCm) {
		this.pidCm = pidCm;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA",  length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO")
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

}
