package com.lowes.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * FacturaGastoViaje generated by hbm2java
 */
@Entity
@Table(name = "LWS584.FACTURA_GASTO_VIAJE")
public class FacturaGastoViaje implements java.io.Serializable {

	private int idFacturaGastoViaje;
	private Factura factura;
	private ViajeConcepto viajeConcepto;
	private ViajeTipoAlimentos viajeTipoAlimentos;
	private Date fechaGasto;
	private String comercio;
	private String ciudad;
	private BigDecimal otrosImpuestos;
	private BigDecimal tua;
	private BigDecimal ish;
	private BigDecimal yri;
	private Short segundaAprobacion;
	private Short desglosar;
	private Integer numeroPersonas;
	private Short activo;
	private Date creacionFecha;
	private Integer creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public FacturaGastoViaje() {
	}

	public FacturaGastoViaje(int idFacturaGastoViaje) {
		this.idFacturaGastoViaje = idFacturaGastoViaje;
	}

	public FacturaGastoViaje(int idFacturaGastoViaje, Factura factura, ViajeConcepto viajeConcepto,
			ViajeTipoAlimentos viajeTipoAlimentos, Date fechaGasto, String comercio, String ciudad,
			BigDecimal otrosImpuestos, BigDecimal tua, BigDecimal ish, BigDecimal yri, Short segundaAprobacion,
			Short desglosar, Integer numeroPersonas, Short activo, Date creacionFecha, Integer creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario) {
		this.idFacturaGastoViaje = idFacturaGastoViaje;
		this.factura = factura;
		this.viajeConcepto = viajeConcepto;
		this.viajeTipoAlimentos = viajeTipoAlimentos;
		this.fechaGasto = fechaGasto;
		this.comercio = comercio;
		this.ciudad = ciudad;
		this.otrosImpuestos = otrosImpuestos;
		this.tua = tua;
		this.ish = ish;
		this.yri = yri;
		this.segundaAprobacion = segundaAprobacion;
		this.desglosar = desglosar;
		this.numeroPersonas = numeroPersonas;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_FACTURA_GASTO_VIAJE", unique = true, nullable = false)
	public int getIdFacturaGastoViaje() {
		return this.idFacturaGastoViaje;
	}

	public void setIdFacturaGastoViaje(int idFacturaGastoViaje) {
		this.idFacturaGastoViaje = idFacturaGastoViaje;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_FACTURA")
	public Factura getFactura() {
		return this.factura;
	}

	public void setFactura(Factura factura) {
		this.factura = factura;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CONCEPTO_GASTO")
	public ViajeConcepto getViajeConcepto() {
		return this.viajeConcepto;
	}

	public void setViajeConcepto(ViajeConcepto viajeConcepto) {
		this.viajeConcepto = viajeConcepto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "VIAJE_TIPO_ALIMENTOS")
	public ViajeTipoAlimentos getViajeTipoAlimentos() {
		return this.viajeTipoAlimentos;
	}

	public void setViajeTipoAlimentos(ViajeTipoAlimentos viajeTipoAlimentos) {
		this.viajeTipoAlimentos = viajeTipoAlimentos;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_GASTO", length = 10)
	public Date getFechaGasto() {
		return this.fechaGasto;
	}

	public void setFechaGasto(Date fechaGasto) {
		this.fechaGasto = fechaGasto;
	}

	@Column(name = "COMERCIO", length = 200)
	public String getComercio() {
		return this.comercio;
	}

	public void setComercio(String comercio) {
		this.comercio = comercio;
	}

	@Column(name = "CIUDAD", length = 100)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "OTROS_IMPUESTOS", precision = 12)
	public BigDecimal getOtrosImpuestos() {
		return this.otrosImpuestos;
	}

	public void setOtrosImpuestos(BigDecimal otrosImpuestos) {
		this.otrosImpuestos = otrosImpuestos;
	}

	@Column(name = "TUA", precision = 12)
	public BigDecimal getTua() {
		return this.tua;
	}

	public void setTua(BigDecimal tua) {
		this.tua = tua;
	}

	@Column(name = "ISH", precision = 12)
	public BigDecimal getIsh() {
		return this.ish;
	}

	public void setIsh(BigDecimal ish) {
		this.ish = ish;
	}

	@Column(name = "YRI", precision = 12)
	public BigDecimal getYri() {
		return this.yri;
	}

	public void setYri(BigDecimal yri) {
		this.yri = yri;
	}

	@Column(name = "SEGUNDA_APROBACION")
	public Short getSegundaAprobacion() {
		return this.segundaAprobacion;
	}

	public void setSegundaAprobacion(Short segundaAprobacion) {
		this.segundaAprobacion = segundaAprobacion;
	}

	@Column(name = "DESGLOSAR")
	public Short getDesglosar() {
		return this.desglosar;
	}

	public void setDesglosar(Short desglosar) {
		this.desglosar = desglosar;
	}

	@Column(name = "NUMERO_PERSONAS")
	public Integer getNumeroPersonas() {
		return this.numeroPersonas;
	}

	public void setNumeroPersonas(Integer numeroPersonas) {
		this.numeroPersonas = numeroPersonas;
	}

	@Column(name = "ACTIVO")
	public Short getActivo() {
		return this.activo;
	}

	public void setActivo(Short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO")
	public Integer getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(Integer creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Transient
	public BigDecimal getSumaOtrosImpuestos() {
		return otrosImpuestos.add(tua.add(ish.add(yri)));
	}

}
