package com.lowes.entity;

//Generated 1/03/2016 05:31:01 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
* FacturaKilometraje generated by hbm2java
*/
@Entity
@Table(name = "FACTURA_KILOMETRAJE")
public class FacturaKilometraje implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idFacturaKilometraje;
	private KilometrajeRecorrido kilometrajeRecorrido;
	private Solicitud solicitud;
	private Date kilometrajeFecha;
	private String motivo;
	private Integer numeroViajes;
	private Double kilometrajeRecorridoCalculado;
	private BigDecimal importe;
	private short activo;
	private Date creacionFecha;
	private Integer creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public FacturaKilometraje() {
	}
	
	public FacturaKilometraje(int idFacturaKilometraje) {
		this.idFacturaKilometraje = idFacturaKilometraje;
	}

	public FacturaKilometraje(int idFacturaKilometraje, KilometrajeRecorrido kilometrajeRecorrido, Solicitud solicitud,
			Date kilometrajeFecha, String motivo, Integer numeroViajes, Double kilometrajeRecorridoCalculado, BigDecimal importe,
			short activo, Date creacionFecha, Integer creacionUsuario) {
		this.idFacturaKilometraje = idFacturaKilometraje;
		this.kilometrajeRecorrido = kilometrajeRecorrido;
		this.solicitud = solicitud;
		this.kilometrajeFecha = kilometrajeFecha;
		this.motivo = motivo;
		this.numeroViajes = numeroViajes;
		this.kilometrajeRecorridoCalculado = kilometrajeRecorridoCalculado;
		this.importe = importe;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public FacturaKilometraje(int idFacturaKilometraje, KilometrajeRecorrido kilometrajeRecorrido, Solicitud solicitud,
			Date kilometrajeFecha, String motivo, Integer numeroViajes, Double kilometrajeRecorridoCalculado, BigDecimal importe,
			short activo, Date creacionFecha, Integer creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idFacturaKilometraje = idFacturaKilometraje;
		this.kilometrajeRecorrido = kilometrajeRecorrido;
		this.solicitud = solicitud;
		this.kilometrajeFecha = kilometrajeFecha;
		this.motivo = motivo;
		this.numeroViajes = numeroViajes;
		this.kilometrajeRecorridoCalculado = kilometrajeRecorridoCalculado;
		this.importe = importe;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_FACTURA_KILOMETRAJE", unique = true, nullable = false)
	public int getIdFacturaKilometraje() {
		return this.idFacturaKilometraje;
	}

	public void setIdFacturaKilometraje(int idFacturaKilometraje) {
		this.idFacturaKilometraje = idFacturaKilometraje;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_KILOMETRAJE_RECORRIDO", nullable = false)
	public KilometrajeRecorrido getKilometrajeRecorrido() {
		return this.kilometrajeRecorrido;
	}

	public void setKilometrajeRecorrido(KilometrajeRecorrido kilometrajeRecorrido) {
		this.kilometrajeRecorrido = kilometrajeRecorrido;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "KILOMETRAJE_FECHA", nullable = false, length = 10)
	public Date getKilometrajeFecha() {
		return this.kilometrajeFecha;
	}

	public void setKilometrajeFecha(Date kilometrajeFecha) {
		this.kilometrajeFecha = kilometrajeFecha;
	}

	@Column(name = "MOTIVO", nullable = false, length = 100)
	public String getMotivo() {
		return this.motivo;
	}

	public void setMotivo(String motivo) {
		this.motivo = motivo;
	}

	@Column(name = "NUMERO_VIAJES", nullable = false)
	public Integer getNumeroViajes() {
		return this.numeroViajes;
	}

	public void setNumeroViajes(Integer numeroViajes) {
		this.numeroViajes = numeroViajes;
	}

	@Column(name = "KILOMETRAJE_RECORRIDO", nullable = false, precision = 53, scale = 0)
	public Double getkilometrajeRecorridoCalculado() {
		return this.kilometrajeRecorridoCalculado;
	}

	public void setkilometrajeRecorridoCalculado(Double kilometrajeRecorridoCalculado) {
		this.kilometrajeRecorridoCalculado = kilometrajeRecorridoCalculado;
	}

	@Column(name = "IMPORTE", nullable = false, precision = 17)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public Integer getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(Integer creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

}