package com.lowes.entity;
// Generated 28/12/2015 05:50:04 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringEscapeUtils;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Factura generated by hbm2java
 */
@Entity
@Table(name = "FACTURA", schema = "LWS584")
public class Factura implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int idFactura;
	private Compania companiaByIdCompaniaLibroContable;
	private Compania companiaByIdCompania;
	private CuentaContable cuentaContable;
	private Locacion locacion;
	private Moneda moneda;
	private Proveedor proveedor;
	private Solicitud solicitud;
	private TipoFactura tipoFactura;
	private String factura;
	private String serieFactura;
	private String folioFiscal;
	private Date fechaFactura;
	private BigDecimal subtotal;
	private BigDecimal iva;
	private BigDecimal ieps;
	private BigDecimal total;
	private short conRetenciones;
	private BigDecimal ivaRetenido;
	private BigDecimal isrRetenido;
	private String par;
	private Short trackAsset;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String conceptoGasto;
	private BigDecimal porcentajeIva;
	private BigDecimal porcentajeIeps;
	private List<FacturaDesglose> facturaDesgloses = new ArrayList<FacturaDesglose>();
	private String archivoPDF;
	private String archivoXML;
	private String archivoLibre;
	private ProveedorLibre proveedorLibre;
	
	private String fechaVencimiento;

	public Factura() {
	}
	
	public Factura(int idFactura){
		this.idFactura = idFactura;
	}

	public Factura(int idFactura, Moneda moneda, Solicitud solicitud, String factura, short conRetenciones,
			short activo, Date creacionFecha, int creacionUsuario) {
		this.idFactura = idFactura;
		this.moneda = moneda;
		this.solicitud = solicitud;
		this.factura = factura;
		this.conRetenciones = conRetenciones;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public Factura(int idFactura, Compania companiaByIdCompaniaLibroContable, Compania companiaByIdCompania,
			CuentaContable cuentaContable, Locacion locacion, Moneda moneda, Proveedor proveedor, 
			Solicitud solicitud, TipoFactura tipoFactura, String factura, String serieFactura,
			String folioFiscal, Date fechaFactura, BigDecimal subtotal, BigDecimal iva, BigDecimal ieps,
			BigDecimal total, short conRetenciones, BigDecimal ivaRetenido, BigDecimal isrRetenido, String par,
			Short trackAsset, short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario, String conceptoGasto, BigDecimal porcentajeIva, BigDecimal porcentajeIeps, 
			List<FacturaDesglose> facturaDesgloses) {
		this.idFactura = idFactura;
		this.companiaByIdCompaniaLibroContable = companiaByIdCompaniaLibroContable;
		this.companiaByIdCompania = companiaByIdCompania;
		this.cuentaContable = cuentaContable;
		this.locacion = locacion;
		this.moneda = moneda;
		this.proveedor = proveedor;
		this.solicitud = solicitud;
		this.tipoFactura = tipoFactura;
		this.factura = factura;
		this.serieFactura = serieFactura;
		this.folioFiscal = folioFiscal;
		this.fechaFactura = fechaFactura;
		this.subtotal = subtotal;
		this.iva = iva;
		this.ieps = ieps;
		this.total = total;
		this.conRetenciones = conRetenciones;
		this.ivaRetenido = ivaRetenido;
		this.isrRetenido = isrRetenido;
		this.par = par;
		this.trackAsset = trackAsset;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.conceptoGasto = conceptoGasto;
		this.porcentajeIva = porcentajeIva;
		this.porcentajeIeps = porcentajeIeps;
		this.facturaDesgloses = facturaDesgloses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_FACTURA", unique = true, nullable = false)
	public int getIdFactura() {
		return this.idFactura;
	}

	public void setIdFactura(int idFactura) {
		this.idFactura = idFactura;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_COMPANIA_LIBRO_CONTABLE")
	public Compania getCompaniaByIdCompaniaLibroContable() {
		return this.companiaByIdCompaniaLibroContable;
	}

	public void setCompaniaByIdCompaniaLibroContable(Compania companiaByIdCompaniaLibroContable) {
		this.companiaByIdCompaniaLibroContable = companiaByIdCompaniaLibroContable;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_COMPANIA")
	public Compania getCompaniaByIdCompania() {
		return this.companiaByIdCompania;
	}

	public void setCompaniaByIdCompania(Compania companiaByIdCompania) {
		this.companiaByIdCompania = companiaByIdCompania;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_CUENTA_CONTABLE")
	public CuentaContable getCuentaContable() {
		return this.cuentaContable;
	}

	public void setCuentaContable(CuentaContable cuentaContable) {
		this.cuentaContable = cuentaContable;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_LOCACION")
	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_MONEDA", nullable = false)
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_PROVEEDOR")
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_FACTURA")
	public TipoFactura getTipoFactura() {
		return this.tipoFactura;
	}

	public void setTipoFactura(TipoFactura tipoFactura) {
		this.tipoFactura = tipoFactura;
	}
	
	@Column(name = "FACTURA", nullable = false, length = 25)
	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	@Column(name = "SERIE_FACTURA", length = 10)
	public String getSerieFactura() {
		return this.serieFactura;
	}

	public void setSerieFactura(String serieFactura) {
		this.serieFactura = serieFactura;
	}

	@Column(name = "FOLIO_FISCAL", length = 100)
	public String getFolioFiscal() {
		return this.folioFiscal;
	}

	public void setFolioFiscal(String folioFiscal) {
		this.folioFiscal = folioFiscal;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FECHA_FACTURA", length = 10)
	public Date getFechaFactura() {
		return this.fechaFactura;
	}

	public void setFechaFactura(Date fechaFactura) {
		this.fechaFactura = fechaFactura;
	}

	@Column(name = "SUBTOTAL", precision = 17)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "IVA", precision = 5)
	public BigDecimal getIva() {
		return this.iva;
	}

	public void setIva(BigDecimal iva) {
		this.iva = iva;
	}

	@Column(name = "IEPS", precision = 5)
	public BigDecimal getIeps() {
		return this.ieps;
	}

	public void setIeps(BigDecimal ieps) {
		this.ieps = ieps;
	}

	@Column(name = "TOTAL", precision = 17)
	public BigDecimal getTotal() {
		return this.total;
	}

	public void setTotal(BigDecimal total) {
		this.total = total;
	}

	@Column(name = "CON_RETENCIONES", nullable = false)
	public short getConRetenciones() {
		return this.conRetenciones;
	}

	public void setConRetenciones(short conRetenciones) {
		this.conRetenciones = conRetenciones;
	}

	@Column(name = "IVA_RETENIDO", precision = 5)
	public BigDecimal getIvaRetenido() {
		return this.ivaRetenido;
	}

	public void setIvaRetenido(BigDecimal ivaRetenido) {
		this.ivaRetenido = ivaRetenido;
	}

	@Column(name = "ISR_RETENIDO", precision = 5)
	public BigDecimal getIsrRetenido() {
		return this.isrRetenido;
	}

	public void setIsrRetenido(BigDecimal isrRetenido) {
		this.isrRetenido = isrRetenido;
	}

	@Column(name = "PAR", length = 10)
	public String getPar() {
		return this.par;
	}

	public void setPar(String par) {
		this.par = par;
	}

	@Column(name = "TRACK_ASSET")
	public Short getTrackAsset() {
		return this.trackAsset;
	}

	public void setTrackAsset(Short trackAsset) {
		this.trackAsset = trackAsset;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "CONCEPTO_GASTO", length = 500)
	public String getConceptoGasto() {
		return  this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}
	
	@Column(name = "PORCENTAJE_IVA", precision = 17)
	public BigDecimal getPorcentajeIva() {
		return this.porcentajeIva;
	}

	public void setPorcentajeIva(BigDecimal porcentajeIva) {
		this.porcentajeIva = porcentajeIva;
	}

	@Column(name = "PORCENTAJE_IEPS", precision = 17)
	public BigDecimal getPorcentajeIeps() {
		return this.porcentajeIeps;
	}

	public void setPorcentajeIeps(BigDecimal porcentajeIeps) {
		this.porcentajeIeps = porcentajeIeps;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@OneToMany(mappedBy = "factura")
	public List<FacturaDesglose> getFacturaDesgloses() {
		return this.facturaDesgloses;
	}

	public void setFacturaDesgloses(List<FacturaDesglose> facturaDesgloses) {
		this.facturaDesgloses = facturaDesgloses;
	}
	
	@Transient
	public String getArchivoPDF() {
		return archivoPDF;
	}

	public void setArchivoPDF(String archivoPDF) {
		this.archivoPDF = archivoPDF;
	}
	
	@Transient
	public String getArchivoXML() {
		return archivoXML;
	}

	public void setArchivoXML(String archivoXML) {
		this.archivoXML = archivoXML;
	}
	
	@Transient
	public String getArchivoLibre() {
		return archivoLibre;
	}

	public void setArchivoLibre(String archivoLibre) {
		this.archivoLibre = archivoLibre;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_PROVEEDOR_LIBRE")
	public ProveedorLibre getProveedorLibre() {
		return proveedorLibre;
	}

	public void setProveedorLibre(ProveedorLibre proveedorLibre) {
		this.proveedorLibre = proveedorLibre;
	}

	@Transient
	public String getFechaVencimiento() {
		return fechaVencimiento;
	}

	public void setFechaVencimiento(String fechaVencimiento) {
		this.fechaVencimiento = fechaVencimiento;
	}
	
}