package com.lowes.entity;

//Generated 1/03/2016 11:31:46 AM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
* KilometrajeRecorrido generated by hbm2java
*/
@Entity
@Table(name = "KILOMETRAJE_RECORRIDO")
public class KilometrajeRecorrido implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idKilometrajeRecorrido;
	private KilometrajeUbicacion kilometrajeUbicacionByIdOrigen;
	private KilometrajeUbicacion kilometrajeUbicacionByIdDestino;
	private Integer numeroKilometros;
	private short activo;
	private Date creacionFecha;
	private Integer creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private Usuario usuario;

	public KilometrajeRecorrido() {
	}
	
	public KilometrajeRecorrido(int idKilometrajeRecorrido) {
		this.idKilometrajeRecorrido = idKilometrajeRecorrido;
	}

	public KilometrajeRecorrido(int idKilometrajeRecorrido, KilometrajeUbicacion kilometrajeUbicacionByIdOrigen,
			KilometrajeUbicacion kilometrajeUbicacionByIdDestino, Integer numeroKilometros, short activo,
			Date creacionFecha, Integer creacionUsuario) {
		this.idKilometrajeRecorrido = idKilometrajeRecorrido;
		this.kilometrajeUbicacionByIdOrigen = kilometrajeUbicacionByIdOrigen;
		this.kilometrajeUbicacionByIdDestino = kilometrajeUbicacionByIdDestino;
		this.numeroKilometros = numeroKilometros;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public KilometrajeRecorrido(int idKilometrajeRecorrido, KilometrajeUbicacion kilometrajeUbicacionByIdOrigen,
			KilometrajeUbicacion kilometrajeUbicacionByIdDestino, Integer numeroKilometros, short activo,
			Date creacionFecha, Integer creacionUsuario, Date modificacionFecha, Integer modificacionUsuario) {
		this.idKilometrajeRecorrido = idKilometrajeRecorrido;
		this.kilometrajeUbicacionByIdOrigen = kilometrajeUbicacionByIdOrigen;
		this.kilometrajeUbicacionByIdDestino = kilometrajeUbicacionByIdDestino;
		this.numeroKilometros = numeroKilometros;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_KILOMETRAJE_RECORRIDO", unique = true, nullable = false)
	public int getIdKilometrajeRecorrido() {
		return this.idKilometrajeRecorrido;
	}

	public void setIdKilometrajeRecorrido(int idKilometrajeRecorrido) {
		this.idKilometrajeRecorrido = idKilometrajeRecorrido;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_ORIGEN", nullable = false)
	public KilometrajeUbicacion getKilometrajeUbicacionByIdOrigen() {
		return this.kilometrajeUbicacionByIdOrigen;
	}

	public void setKilometrajeUbicacionByIdOrigen(KilometrajeUbicacion kilometrajeUbicacionByIdOrigen) {
		this.kilometrajeUbicacionByIdOrigen = kilometrajeUbicacionByIdOrigen;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_DESTINO", nullable = false)
	public KilometrajeUbicacion getKilometrajeUbicacionByIdDestino() {
		return this.kilometrajeUbicacionByIdDestino;
	}

	public void setKilometrajeUbicacionByIdDestino(KilometrajeUbicacion kilometrajeUbicacionByIdDestino) {
		this.kilometrajeUbicacionByIdDestino = kilometrajeUbicacionByIdDestino;
	}

	@Column(name = "NUMERO_KILOMETROS", nullable = false)
	public Integer getNumeroKilometros() {
		return this.numeroKilometros;
	}

	public void setNumeroKilometros(Integer numeroKilometros) {
		this.numeroKilometros = numeroKilometros;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public Integer getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(Integer creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

}