package com.lowes.entity;

//default package
//Generated 14/12/2015 01:36:27 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
* Moneda generated by hbm2java
*/
@Entity
@Table(name = "MONEDA")
public class Moneda implements java.io.Serializable {

	private static final long serialVersionUID = -5553917959866747329L;
	
	private int idMoneda;
	private String descripcion;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String descripcionCorta;
	private String descripcionCortaVariantes;
	//solo para vista
	private int idTipoMoneda;

	public Moneda() { // constructor
	}
	
	public Moneda(int idMoneda) { // constructor
		this.idMoneda = idMoneda;
	}

	public Moneda(int idMoneda, String descripcion, short activo, Date creacionFecha, int creacionUsuario, String descripcionCorta) {
		this.idMoneda = idMoneda;
		this.descripcion = descripcion;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.descripcionCorta = descripcionCorta;
	}

	public Moneda(int idMoneda, String descripcion, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario, String descripcionCorta) {
		this.idMoneda = idMoneda;
		this.descripcion = descripcion;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.descripcionCorta = descripcionCorta;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_MONEDA", unique = true, nullable = false)
	public int getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(int idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "DESCRIPCION_CORTA", nullable = false, length = 10)
	public String getDescripcionCorta() {
		return this.descripcionCorta;
	}

	public void setDescripcionCorta(String descripcionCorta) {
		this.descripcionCorta = descripcionCorta;
	}
	
	@Column(name = "DESCRIPCION_CORTA_VARIANTES", nullable = false, length = 100)
	public String getDescripcionCortaVariantes() {
		return descripcionCortaVariantes;
	}

	public void setDescripcionCortaVariantes(String descripcionCortaVariantes) {
		this.descripcionCortaVariantes = descripcionCortaVariantes;
	}

	@Transient
	public int getIdTipoMoneda() {
		return idTipoMoneda;
	}

	public void setIdTipoMoneda(int idTipoMoneda) {
		this.idTipoMoneda = idTipoMoneda;
	}
	
    @Override
    public boolean equals( Object obj )
    {
        if ( obj != null && obj instanceof Moneda )
        {
        	Moneda otroMoneda = ( Moneda ) obj;
            return otroMoneda.getIdMoneda() == this.getIdMoneda();
        }
        else
        {
            return false;
        }
    }

}
