package com.lowes.entity;

// default package
// Generated 18/12/2015 01:08:54 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NivelAutoriza generated by hbm2java
 */
@Entity
@Table(name = "NIVEL_AUTORIZA", schema = "LWS584")
public class NivelAutoriza implements java.io.Serializable {

	private static final long serialVersionUID = 796673836712216722L;

	private int idNivelAutoriza;
	private BigDecimal dolaresLimite;
	private BigDecimal pesosLimite;
	private int inferiorSuperior;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public NivelAutoriza() {
	}

	public NivelAutoriza(int idNivelAutoriza, BigDecimal dolaresLimite, BigDecimal pesosLimite, int inferiorSuperior,
			short activo, Date creacionFecha, int creacionUsuario) {
		this.idNivelAutoriza = idNivelAutoriza;
		this.dolaresLimite = dolaresLimite;
		this.pesosLimite = pesosLimite;
		this.inferiorSuperior = inferiorSuperior;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public NivelAutoriza(int idNivelAutoriza, BigDecimal dolaresLimite, BigDecimal pesosLimite, int inferiorSuperior,
			short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idNivelAutoriza = idNivelAutoriza;
		this.dolaresLimite = dolaresLimite;
		this.pesosLimite = pesosLimite;
		this.inferiorSuperior = inferiorSuperior;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_NIVEL_AUTORIZA", unique = true, nullable = false)
	public int getIdNivelAutoriza() {
		return this.idNivelAutoriza;
	}

	public void setIdNivelAutoriza(int idNivelAutoriza) {
		this.idNivelAutoriza = idNivelAutoriza;
	}

	@Column(name = "DOLARES_LIMITE", nullable = false, precision = 17)
	public BigDecimal getDolaresLimite() {
		return this.dolaresLimite;
	}

	public void setDolaresLimite(BigDecimal dolaresLimite) {
		this.dolaresLimite = dolaresLimite;
	}

	@Column(name = "PESOS_LIMITE", nullable = false, precision = 17)
	public BigDecimal getPesosLimite() {
		return this.pesosLimite;
	}

	public void setPesosLimite(BigDecimal pesosLimite) {
		this.pesosLimite = pesosLimite;
	}

	@Column(name = "INFERIOR_SUPERIOR", nullable = false)
	public int getInferiorSuperior() {
		return this.inferiorSuperior;
	}

	public void setInferiorSuperior(int inferiorSuperior) {
		this.inferiorSuperior = inferiorSuperior;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
}