/**
 * 
 */
package com.lowes.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
* Proveedor generated by hbm2java
*/
@Entity
@Table(name = "PROVEEDOR", schema = "LWS584")
public class Proveedor implements java.io.Serializable {

	private static final long serialVersionUID = -8251115925720744397L;

	private int idProveedor;
	private int numeroProveedor;
	private Locacion locacion;
	private TipoProveedor tipoProveedor;
	private String descripcion;
	private String contacto;
	private String correoElectronico;
	private short proveedorRiesgo;
	private short activo;
	private short permiteAnticipoMultiple;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String rfc;
	private Usuario usuario;
	private String numeroDescripcionProveedor;
	
	
//	ID's de objetos 
	private int idUsuario;
	
	private Boolean permiteAnticipoMultipleB;

	public Proveedor() {
	}
	
	public Proveedor(int idProveedor) {
		this.idProveedor = idProveedor;
	}

	public Proveedor(int idProveedor, TipoProveedor tipoProveedor, int numeroProveedor, String descripcion, String contacto,
			String correoElectronico, short proveedorRiesgo, short activo, Date creacionFecha,
			int creacionUsuario, String rfc, short permiteAnticipoMultiple) {
		this.idProveedor = idProveedor;
		this.tipoProveedor = tipoProveedor;
		this.numeroProveedor = numeroProveedor;
		this.descripcion = descripcion;
		this.contacto = contacto;
		this.correoElectronico = correoElectronico;
		this.proveedorRiesgo = proveedorRiesgo;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.rfc = rfc;
		this.permiteAnticipoMultiple = permiteAnticipoMultiple;
	}

	public Proveedor(int idProveedor, Locacion locacion, TipoProveedor tipoProveedor, Usuario usuario,int numeroProveedor, 
			String descripcion, String contacto, String correoElectronico, short proveedorRiesgo, short activo, 
			Date creacionFecha, int creacionUsuario, Date modificacionFecha, Integer modificacionUsuario, String rfc,
			short permiteAnticipoMultiple) {
		this.idProveedor = idProveedor;
		this.locacion = locacion;
		this.tipoProveedor = tipoProveedor;
		this.usuario = usuario;
		this.numeroProveedor = numeroProveedor;
		this.descripcion = descripcion;
		this.contacto = contacto;
		this.correoElectronico = correoElectronico;
		this.proveedorRiesgo = proveedorRiesgo;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.rfc = rfc;
		this.permiteAnticipoMultiple = permiteAnticipoMultiple;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_PROVEEDOR", unique = true, nullable = false)
	public int getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(int idProveedor) {
		this.idProveedor = idProveedor;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO_AUTORIZA")
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_LOCACION")
	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_PROVEEDOR", nullable = false)
	public TipoProveedor getTipoProveedor() {
		return this.tipoProveedor;
	}

	public void setTipoProveedor(TipoProveedor tipoProveedor) {
		this.tipoProveedor = tipoProveedor;
	}

	@Column(name = "NUMERO_PROVEEDOR", nullable = false)
	public int getNumeroProveedor() {
		return this.numeroProveedor;
	}

	public void setNumeroProveedor(int numeroProveedor) {
		this.numeroProveedor = numeroProveedor;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "CONTACTO", nullable = false, length = 100)
	public String getContacto() {
		return this.contacto;
	}

	public void setContacto(String contacto) {
		this.contacto = contacto;
	}

	@Column(name = "CORREO_ELECTRONICO", nullable = false, length = 50)
	public String getCorreoElectronico() {
		return this.correoElectronico;
	}

	public void setCorreoElectronico(String correoElectronico) {
		this.correoElectronico = correoElectronico;
	}

	@Column(name = "PROVEEDOR_RIESGO", nullable = false)
	public short getProveedorRiesgo() {
		return this.proveedorRiesgo;
	}

	public void setProveedorRiesgo(short proveedorRiesgo) {
		this.proveedorRiesgo = proveedorRiesgo;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "RFC", nullable = false, length = 15)
	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}
	
	@Column(name = "PERMITE_ANTICIPO_MULTIPLE", nullable = false)
	public short getPermiteAnticipoMultiple() {
		return this.permiteAnticipoMultiple;
	}

	public void setPermiteAnticipoMultiple(short permiteAnticipoMultiple) {
		this.permiteAnticipoMultiple = permiteAnticipoMultiple;
	}
	
	@Transient
	public int getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}
	
	@Transient
	public String getNumeroDescripcionProveedor() {
		numeroDescripcionProveedor = this.numeroProveedor + " - " + this.descripcion;
		return numeroDescripcionProveedor;
	}

	public void setNumeroDescripcionProveedor(String numeroDescripcionProveedor) {
		this.numeroDescripcionProveedor = numeroDescripcionProveedor;
	}

	@Transient
	public Boolean getPermiteAnticipoMultipleB() {
		return permiteAnticipoMultipleB;
	}

	public void setPermiteAnticipoMultipleB(Boolean permiteAnticipoMultipleB) {
		this.permiteAnticipoMultipleB = permiteAnticipoMultipleB;
	}
	
}