package com.lowes.entity;
// Generated 28/12/2015 05:50:04 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * SolicitudArchivo generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_ARCHIVO", schema = "LWS584")
public class SolicitudArchivo implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idSolicitudArchivo;
	private Solicitud solicitud;
	private String descripcion;
	private String archivo;
	private String pidCm;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	
//	ID's de objetos
	private int idSolicitud;

	public SolicitudArchivo() {
	}

	public SolicitudArchivo(int idSolicitudArchivo, Solicitud solicitud, String descripcion, String archivo,
			short activo, Date creacionFecha, int creacionUsuario) {
		this.idSolicitudArchivo = idSolicitudArchivo;
		this.solicitud = solicitud;
		this.descripcion = descripcion;
		this.archivo = archivo;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public SolicitudArchivo(int idSolicitudArchivo, Solicitud solicitud, String descripcion, String archivo,
			String pidCm, short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idSolicitudArchivo = idSolicitudArchivo;
		this.solicitud = solicitud;
		this.descripcion = descripcion;
		this.archivo = archivo;
		this.pidCm = pidCm;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_SOLICITUD_ARCHIVO", unique = true, nullable = false)
	public int getIdSolicitudArchivo() {
		return this.idSolicitudArchivo;
	}

	public void setIdSolicitudArchivo(int idSolicitudArchivo) {
		this.idSolicitudArchivo = idSolicitudArchivo;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ARCHIVO", nullable = false, length = 100)
	public String getArchivo() {
		return this.archivo;
	}

	public void setArchivo(String archivo) {
		this.archivo = archivo;
	}

	@Column(name = "PID_CM", length = 250)
	public String getPidCm() {
		return this.pidCm;
	}

	public void setPidCm(String pidCm) {
		this.pidCm = pidCm;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

	@Transient
	public int getIdSolicitud() {
		return idSolicitud;
	}

	public void setIdSolicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

}
