package com.lowes.entity;

// default package
// Generated 21-abr-2016 12:23:15 by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * SolicitudAnticipoViaje generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_ANTICIPO_VIAJE")
public class SolicitudAnticipoViaje implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSolicitudAnticipoViaje;
	private Solicitud solicitud;
	private ViajeDestino viajeDestino;
	private ViajeMotivo viajeMotivo;
	private Date inicioFecha;
	private Date finFecha;
	private int numPersonas;
	private String motivoCotizacion;
	private int idSolicitudAerolineaSeleccionado;
	private String descripcionOtro;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String descripcionOtroMotivo;
	private String descripcionOtroDestino;
	private String resultadoViaje;
	private Short preguntaExtrangero1;
	private Short preguntaExtrangero2;

	public SolicitudAnticipoViaje() {
	}

	public SolicitudAnticipoViaje(int idSolicitudAnticipoViaje, Solicitud solicitud, ViajeDestino viajeDestino,
			ViajeMotivo viajeMotivo, Date inicioFecha, Date finFecha, int numPersonas,
			int idSolicitudAerolineaSeleccionado, short activo, Date creacionFecha, int creacionUsuario) {
		this.idSolicitudAnticipoViaje = idSolicitudAnticipoViaje;
		this.solicitud = solicitud;
		this.viajeDestino = viajeDestino;
		this.viajeMotivo = viajeMotivo;
		this.inicioFecha = inicioFecha;
		this.finFecha = finFecha;
		this.numPersonas = numPersonas;
		this.idSolicitudAerolineaSeleccionado = idSolicitudAerolineaSeleccionado;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public SolicitudAnticipoViaje(int idSolicitudAnticipoViaje, Solicitud solicitud, ViajeDestino viajeDestino,
			ViajeMotivo viajeMotivo, Date inicioFecha, Date finFecha, int numPersonas, String motivoCotizacion,
			int idSolicitudAerolineaSeleccionado, String descripcionOtro, short activo, Date creacionFecha,
			int creacionUsuario, Date modificacionFecha, Integer modificacionUsuario) {
		this.idSolicitudAnticipoViaje = idSolicitudAnticipoViaje;
		this.solicitud = solicitud;
		this.viajeDestino = viajeDestino;
		this.viajeMotivo = viajeMotivo;
		this.inicioFecha = inicioFecha;
		this.finFecha = finFecha;
		this.numPersonas = numPersonas;
		this.motivoCotizacion = motivoCotizacion;
		this.idSolicitudAerolineaSeleccionado = idSolicitudAerolineaSeleccionado;
		this.descripcionOtro = descripcionOtro;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_SOLICITUD_ANTICIPO_VIAJE", unique = true, nullable = false)
	public int getIdSolicitudAnticipoViaje() {
		return this.idSolicitudAnticipoViaje;
	}

	public void setIdSolicitudAnticipoViaje(int idSolicitudAnticipoViaje) {
		this.idSolicitudAnticipoViaje = idSolicitudAnticipoViaje;
	}

	@ManyToOne
	@LazyCollection(LazyCollectionOption.FALSE)
	@JoinColumn(name = "ID_SOLICITUD", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@ManyToOne
	@LazyCollection(LazyCollectionOption.FALSE)
	@JoinColumn(name = "ID_VIAJE_DESTINO", nullable = false)
	public ViajeDestino getViajeDestino() {
		return this.viajeDestino;
	}

	public void setViajeDestino(ViajeDestino viajeDestino) {
		this.viajeDestino = viajeDestino;
	}

	@ManyToOne
	@LazyCollection(LazyCollectionOption.FALSE)
	@JoinColumn(name = "ID_VIAJE_MOTIVO", nullable = false)
	public ViajeMotivo getViajeMotivo() {
		return this.viajeMotivo;
	}

	public void setViajeMotivo(ViajeMotivo viajeMotivo) {
		this.viajeMotivo = viajeMotivo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "INICIO_FECHA", nullable = false, length = 10)
	public Date getInicioFecha() {
		return this.inicioFecha;
	}

	public void setInicioFecha(Date inicioFecha) {
		this.inicioFecha = inicioFecha;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FIN_FECHA", nullable = false, length = 10)
	public Date getFinFecha() {
		return this.finFecha;
	}

	public void setFinFecha(Date finFecha) {
		this.finFecha = finFecha;
	}

	@Column(name = "NUM_PERSONAS", nullable = false)
	public int getNumPersonas() {
		return this.numPersonas;
	}

	public void setNumPersonas(int numPersonas) {
		this.numPersonas = numPersonas;
	}

	@Column(name = "MOTIVO_COTIZACION", length = 500)
	public String getMotivoCotizacion() {
		return this.motivoCotizacion;
	}

	public void setMotivoCotizacion(String motivoCotizacion) {
		this.motivoCotizacion = motivoCotizacion;
	}

	@Column(name = "ID_SOLICITUD_AEROLINEA_SELECCIONADO", nullable = false)
	public int getIdSolicitudAerolineaSeleccionado() {
		return this.idSolicitudAerolineaSeleccionado;
	}

	public void setIdSolicitudAerolineaSeleccionado(int idSolicitudAerolineaSeleccionado) {
		this.idSolicitudAerolineaSeleccionado = idSolicitudAerolineaSeleccionado;
	}

	@Column(name = "DESCRIPCION_OTRO", length = 100)
	public String getDescripcionOtro() {
		return this.descripcionOtro;
	}

	public void setDescripcionOtro(String descripcionOtro) {
		this.descripcionOtro = descripcionOtro;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	
	@Column(name = "RESULTADO_VIAJE", length = 500)
	public String getResultadoViaje() {
		return this.resultadoViaje;
	}

	public void setResultadoViaje(String resultadoViaje) {
		this.resultadoViaje = resultadoViaje;
	}

	@Column(name = "PREGUNTA_EXTRANGERO1")
	public Short getPreguntaExtrangero1() {
		return this.preguntaExtrangero1;
	}

	public void setPreguntaExtrangero1(Short preguntaExtrangero1) {
		this.preguntaExtrangero1 = preguntaExtrangero1;
	}

	@Column(name = "PREGUNTA_EXTRANGERO2")
	public Short getPreguntaExtrangero2() {
		return this.preguntaExtrangero2;
	}

	public void setPreguntaExtrangero2(Short preguntaExtrangero2) {
		this.preguntaExtrangero2 = preguntaExtrangero2;
	}
	
	@Column(name = "DESCRIPCION_OTRO_MOTIVO", length = 100)
	public String getDescripcionOtroMotivo() {
		return descripcionOtroMotivo;
	}

	public void setDescripcionOtroMotivo(String descripcionOtroMotivo) {
		this.descripcionOtroMotivo = descripcionOtroMotivo;
	}
	
	@Column(name = "DESCRIPCION_OTRO_DESTINO", length = 100)
	public String getDescripcionOtroDestino() {
		return descripcionOtroDestino;
	}

	public void setDescripcionOtroDestino(String descripcionOtroDestino) {
		this.descripcionOtroDestino = descripcionOtroDestino;
	}

}
