package com.lowes.entity;
// Generated 28/12/2015 05:50:04 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.apache.commons.lang3.StringEscapeUtils;
import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * Solicitud generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD", schema = "LWS584")
public class Solicitud implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idSolicitud;
	private EstadoSolicitud estadoSolicitud;
	private TipoSolicitud tipoSolicitud;
	private Usuario usuarioByIdUsuario;
	private Usuario usuarioByIdUsuarioSolicita;
	private Usuario usuarioByIdUsuarioAsesor;
	private Proveedor proveedor;
	private TipoProveedor tipoProveedor;
	private Compania compania;
	private FormaPago formaPago;
	private Locacion locacion;
	private Moneda moneda;
	private String conceptoGasto;
	private BigDecimal montoTotal;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String motivoRechazo;
	private Integer enviado_CM;
	private Integer comprobada;
	private short trackAsset;
	private Date fechaPago;
	private Short segundaAprobacion;
	private boolean urlVisible;

	
	private List<Factura> facturas = new ArrayList<Factura>();
	private List<SolicitudAutorizacion> solicitudAutorizacion = new ArrayList<SolicitudAutorizacion>();
	private List<FacturaKilometraje> facturaKilometraje = new ArrayList<>();

//	ID's de objetos
	private int idEstadoSolicitud;
	private int idTipoSolicitud;
	private int idUsuario;
	private int idUsuarioSolicita;
	private int idcompania;
	private int idFormaPago;
	private int idLocacion;
	private int idMoneda;
	private ComprobacionDeposito comprobacion;
	public Solicitud() {
	}
	
	
	public Solicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	

	public Solicitud(int idSolicitud, EstadoSolicitud estadoSolicitud, TipoSolicitud tipoSolicitud,
			Usuario usuarioByIdUsuario, short activo, Date creacionFecha, int creacionUsuario, short trackAsset) {
		this.idSolicitud = idSolicitud;
		this.estadoSolicitud = estadoSolicitud;
		this.tipoSolicitud = tipoSolicitud;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.trackAsset = trackAsset;
	}

	public Solicitud(int idSolicitud, Compania compania, EstadoSolicitud estadoSolicitud, FormaPago formaPago,
			Locacion locacion, Moneda moneda, TipoSolicitud tipoSolicitud, Usuario usuarioByIdUsuario,
			Usuario usuarioByIdUsuarioSolicita, Usuario usuarioByIdUsuarioAsesor, Proveedor proveedor, 
			TipoProveedor tipoProveedor, String conceptoGasto, BigDecimal montoTotal, short activo, 
			Date creacionFecha, int creacionUsuario, Date modificacionFecha, Integer modificacionUsuario,
			String motivoRechazo, short trackAsset, Date fechaPago, List<Factura> facturas) {
		this.idSolicitud = idSolicitud;
		this.compania = compania;
		this.estadoSolicitud = estadoSolicitud;
		this.formaPago = formaPago;
		this.locacion = locacion;
		this.moneda = moneda;
		this.tipoSolicitud = tipoSolicitud;
		this.usuarioByIdUsuario = usuarioByIdUsuario;
		this.usuarioByIdUsuarioSolicita = usuarioByIdUsuarioSolicita;
		this.usuarioByIdUsuarioAsesor = usuarioByIdUsuarioAsesor;
		this.proveedor = proveedor;
		this.tipoProveedor = tipoProveedor;
		this.conceptoGasto = conceptoGasto;
		this.montoTotal = montoTotal;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.motivoRechazo = motivoRechazo;
		this.trackAsset = trackAsset;
		this.fechaPago = fechaPago;
		this.facturas = facturas;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_SOLICITUD", unique = true, nullable = false)
	public int getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_COMPANIA")
	public Compania getCompania() {
		return this.compania;
	}

	public void setCompania(Compania compania) {
		this.compania = compania;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_ESTADO_SOLICITUD", nullable = false)
	public EstadoSolicitud getEstadoSolicitud() {
		return this.estadoSolicitud;
	}

	public void setEstadoSolicitud(EstadoSolicitud estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_LOCACION")
	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_MONEDA")
	public Moneda getMoneda() {
		return this.moneda;
	}

	public void setMoneda(Moneda moneda) {
		this.moneda = moneda;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_FORMA_PAGO")
	public FormaPago getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(FormaPago formaPago) {
		this.formaPago = formaPago;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_PROVEEDOR")
	public Proveedor getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(Proveedor proveedor) {
		this.proveedor = proveedor;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_PROVEEDOR")
	public TipoProveedor getTipoProveedor() {
		return this.tipoProveedor;
	}

	public void setTipoProveedor(TipoProveedor tipoProveedor) {
		this.tipoProveedor = tipoProveedor;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_SOLICITUD", nullable = false)
	public TipoSolicitud getTipoSolicitud() {
		return this.tipoSolicitud;
	}

	public void setTipoSolicitud(TipoSolicitud tipoSolicitud) {
		this.tipoSolicitud = tipoSolicitud;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO", nullable = false)
	public Usuario getUsuarioByIdUsuario() {
		return this.usuarioByIdUsuario;
	}

	public void setUsuarioByIdUsuario(Usuario usuarioByIdUsuario) {
		this.usuarioByIdUsuario = usuarioByIdUsuario;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO_SOLICITA")
	public Usuario getUsuarioByIdUsuarioSolicita() {
		return this.usuarioByIdUsuarioSolicita;
	}

	public void setUsuarioByIdUsuarioSolicita(Usuario usuarioByIdUsuarioSolicita) {
		this.usuarioByIdUsuarioSolicita = usuarioByIdUsuarioSolicita;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO_ASESOR")
	public Usuario getUsuarioByIdUsuarioAsesor() {
		return this.usuarioByIdUsuarioAsesor;
	}

	public void setUsuarioByIdUsuarioAsesor(Usuario usuarioByIdUsuarioAsesor) {
		this.usuarioByIdUsuarioAsesor = usuarioByIdUsuarioAsesor;
	}

	@Column(name = "CONCEPTO_GASTO")
	public String getConceptoGasto() {
		return this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}

	@Column(name = "MONTO_TOTAL", precision = 17)
	public BigDecimal getMontoTotal() {
		return this.montoTotal;
	}

	public void setMontoTotal(BigDecimal montoTotal) {
		this.montoTotal = montoTotal;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO")
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "MOTIVO_RECHAZO", length = 500)
	public String getMotivoRechazo() {
		return this.motivoRechazo;
	}

	public void setMotivoRechazo(String motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}
	
	@Column(name = "TRACK_ASSET", nullable = false)
	public short getTrackAsset() {
		return this.trackAsset;
	}

	public void setTrackAsset(short trackAsset) {
		this.trackAsset = trackAsset;
	}
	
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_PAGO", length = 26)
	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@OneToMany(mappedBy = "solicitud")
	public List<Factura> getFacturas() {
		return this.facturas;
	}

	public void setFacturas(List<Factura> facturas) {
		this.facturas = facturas;
	}
	
	@LazyCollection(LazyCollectionOption.FALSE)
	@OneToMany(mappedBy = "solicitud")
	public List<SolicitudAutorizacion> getSolicitudAutorizacion() {
		return solicitudAutorizacion;
	}


	public void setSolicitudAutorizacion(List<SolicitudAutorizacion> solicitudAutorizacion) {
		this.solicitudAutorizacion = solicitudAutorizacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@OneToMany(mappedBy = "solicitud")
	public List<FacturaKilometraje> getFacturaKilometraje() {
		return facturaKilometraje;
	}


	public void setFacturaKilometraje(List<FacturaKilometraje> facturaKilometraje) {
		this.facturaKilometraje = facturaKilometraje;
	}


	@Transient
	public int getIdEstadoSolicitud() {
		return idEstadoSolicitud;
	}

	public void setIdEstadoSolicitud(int idEstadoSolicitud) {
		this.idEstadoSolicitud = idEstadoSolicitud;
	}

	@Transient
	public int getIdTipoSolicitud() {
		return idTipoSolicitud;
	}

	public void setIdTipoSolicitud(int idTipoSolicitud) {
		this.idTipoSolicitud = idTipoSolicitud;
	}

	@Transient
	public int getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Transient
	public int getIdUsuarioSolicita() {
		return idUsuarioSolicita;
	}

	public void setIdUsuarioSolicita(int idUsuarioSolicita) {
		this.idUsuarioSolicita = idUsuarioSolicita;
	}

	@Transient
	public int getIdcompania() {
		return idcompania;
	}

	public void setIdcompania(int idcompania) {
		this.idcompania = idcompania;
	}

	@Transient
	public int getIdFormaPago() {
		return idFormaPago;
	}

	public void setIdFormaPago(int idFormaPago) {
		this.idFormaPago = idFormaPago;
	}

	@Transient
	public int getIdLocacion() {
		return idLocacion;
	}

	public void setIdLocacion(int idLocacion) {
		this.idLocacion = idLocacion;
	}

	@Transient
	public int getIdMoneda() {
		return idMoneda;
	}

	public void setIdMoneda(int idMoneda) {
		this.idMoneda = idMoneda;
	}


	/**
	 * @return the enviado_CM
	 */
	public Integer getEnviado_CM() {
		return enviado_CM;
	}


	/**
	 * @param enviado_CM the enviado_CM to set
	 */
	public void setEnviado_CM(Integer enviado_CM) {
		this.enviado_CM = enviado_CM;
	}


	/**
	 * @return the comprobada
	 */
	public Integer getComprobada() {
		return comprobada;
	}


	/**
	 * @param comprobada the comprobada to set
	 */
	public void setComprobada(Integer comprobada) {
		this.comprobada = comprobada;
	}

	@Column(name = "SEGUNDA_APROBACION")
	public Short getSegundaAprobacion() {
		return segundaAprobacion;
	}


	public void setSegundaAprobacion(Short segundaAprobacion) {
		this.segundaAprobacion = segundaAprobacion;
	}

	@Transient
	public boolean isUrlVisible() {
		return urlVisible;
	}


	public void setUrlVisible(boolean urlVisible) {
		this.urlVisible = urlVisible;
	}
	@Transient
	public ComprobacionDeposito getComprobacion() {
		return comprobacion;
	}
	
	public void setComprobacion(ComprobacionDeposito comprobacion) {
		this.comprobacion = comprobacion;
	}
	
}

