package com.lowes.entity;

// default package
// Generated 21-abr-2016 12:23:15 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * SolicitudAnticipoViajeConceptos generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_ANTICIPO_VIAJE_CONCEPTOS")
public class SolicitudAnticipoViajeConceptos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSolicitudAnticipoViajeConceptos;
	private SolicitudAnticipoViaje solicitudAnticipoViaje;
	private ViajeConcepto viajeConcepto;
	private BigDecimal importe;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public SolicitudAnticipoViajeConceptos() {
	}
	
	public SolicitudAnticipoViajeConceptos(int idSolicitudAnticipoViajeConceptos) {
		this.idSolicitudAnticipoViajeConceptos = idSolicitudAnticipoViajeConceptos;
	}

	public SolicitudAnticipoViajeConceptos(int idSolicitudAnticipoViajeConceptos,
			SolicitudAnticipoViaje solicitudAnticipoViaje, ViajeConcepto viajeConcepto, short activo,
			Date creacionFecha, int creacionUsuario) {
		this.idSolicitudAnticipoViajeConceptos = idSolicitudAnticipoViajeConceptos;
		this.solicitudAnticipoViaje = solicitudAnticipoViaje;
		this.viajeConcepto = viajeConcepto;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public SolicitudAnticipoViajeConceptos(int idSolicitudAnticipoViajeConceptos,
			SolicitudAnticipoViaje solicitudAnticipoViaje, ViajeConcepto viajeConcepto, BigDecimal importe,
			short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idSolicitudAnticipoViajeConceptos = idSolicitudAnticipoViajeConceptos;
		this.solicitudAnticipoViaje = solicitudAnticipoViaje;
		this.viajeConcepto = viajeConcepto;
		this.importe = importe;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_SOLICITUD_ANTICIPO_VIAJE_CONCEPTOS", unique = true, nullable = false)
	public int getIdSolicitudAnticipoViajeConceptos() {
		return this.idSolicitudAnticipoViajeConceptos;
	}

	public void setIdSolicitudAnticipoViajeConceptos(int idSolicitudAnticipoViajeConceptos) {
		this.idSolicitudAnticipoViajeConceptos = idSolicitudAnticipoViajeConceptos;
	}

	@ManyToOne
	@LazyCollection(LazyCollectionOption.FALSE)
	@JoinColumn(name = "ID_SOLICITUD_ANTICIPO_VIAJE", nullable = false)
	public SolicitudAnticipoViaje getSolicitudAnticipoViaje() {
		return this.solicitudAnticipoViaje;
	}

	public void setSolicitudAnticipoViaje(SolicitudAnticipoViaje solicitudAnticipoViaje) {
		this.solicitudAnticipoViaje = solicitudAnticipoViaje;
	}

	@ManyToOne
	@LazyCollection(LazyCollectionOption.FALSE)
	@JoinColumn(name = "ID_VIAJE_CONCEPTO", nullable = false)
	public ViajeConcepto getViajeConcepto() {
		return this.viajeConcepto;
	}

	public void setViajeConcepto(ViajeConcepto viajeConcepto) {
		this.viajeConcepto = viajeConcepto;
	}

	@Column(name = "IMPORTE", precision = 17)
	public BigDecimal getImporte() {
		return this.importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

}
