package com.lowes.entity;

// default package
// Generated 21-abr-2016 12:23:15 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * SolicitudAnticipoViajeAerolinea generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_ANTICIPO_VIAJE_AEROLINEA")
public class SolicitudAnticipoViajeAerolinea implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idSolicitudAnticipoViajeAerolinea;
	private SolicitudAnticipoViaje solicitudAnticipoViaje;
	private String nombreAerolinea;
	private BigDecimal costoAerolinea;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;

	public SolicitudAnticipoViajeAerolinea() {
	}
	
	public SolicitudAnticipoViajeAerolinea(int idSolicitudAnticipoViajeAerolinea) {
		this.idSolicitudAnticipoViajeAerolinea = idSolicitudAnticipoViajeAerolinea;
	}

	public SolicitudAnticipoViajeAerolinea(int idSolicitudAnticipoViajeAerolinea,
			SolicitudAnticipoViaje solicitudAnticipoViaje, short activo, Date creacionFecha, int creacionUsuario) {
		this.idSolicitudAnticipoViajeAerolinea = idSolicitudAnticipoViajeAerolinea;
		this.solicitudAnticipoViaje = solicitudAnticipoViaje;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public SolicitudAnticipoViajeAerolinea(int idSolicitudAnticipoViajeAerolinea,
			SolicitudAnticipoViaje solicitudAnticipoViaje, String nombreAerolinea, BigDecimal costoAerolinea,
			short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idSolicitudAnticipoViajeAerolinea = idSolicitudAnticipoViajeAerolinea;
		this.solicitudAnticipoViaje = solicitudAnticipoViaje;
		this.nombreAerolinea = nombreAerolinea;
		this.costoAerolinea = costoAerolinea;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_SOLICITUD_ANTICIPO_VIAJE_AEROLINEA", unique = true, nullable = false)
	public int getIdSolicitudAnticipoViajeAerolinea() {
		return this.idSolicitudAnticipoViajeAerolinea;
	}

	public void setIdSolicitudAnticipoViajeAerolinea(int idSolicitudAnticipoViajeAerolinea) {
		this.idSolicitudAnticipoViajeAerolinea = idSolicitudAnticipoViajeAerolinea;
	}

	@ManyToOne
	@LazyCollection(LazyCollectionOption.FALSE)
	@JoinColumn(name = "ID_SOLICITUD_ANTICIPO_VIAJE", nullable = false)
	public SolicitudAnticipoViaje getSolicitudAnticipoViaje() {
		return this.solicitudAnticipoViaje;
	}

	public void setSolicitudAnticipoViaje(SolicitudAnticipoViaje solicitudAnticipoViaje) {
		this.solicitudAnticipoViaje = solicitudAnticipoViaje;
	}

	@Column(name = "NOMBRE_AEROLINEA", length = 100)
	public String getNombreAerolinea() {
		return this.nombreAerolinea;
	}

	public void setNombreAerolinea(String nombreAerolinea) {
		this.nombreAerolinea = nombreAerolinea;
	}

	@Column(name = "COSTO_AEROLINEA", precision = 17)
	public BigDecimal getCostoAerolinea() {
		return this.costoAerolinea;
	}

	public void setCostoAerolinea(BigDecimal costoAerolinea) {
		this.costoAerolinea = costoAerolinea;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

}
