package com.lowes.entity;
// Generated 28/12/2015 05:50:04 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * SolicitudAutorizacion generated by hbm2java
 */
@Entity
@Table(name = "SOLICITUD_AUTORIZACION", schema = "LWS584")
public class SolicitudAutorizacion implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private int idSolicitudAutorizacion;
	private EstadoAutorizacion estadoAutorizacion;
	private EstadoSolicitud estadoSolicitud;
	private Solicitud solicitud;
	private TipoCriterio tipoCriterio;
	private Usuario usuarioByIdUsuarioAutoriza;
	private Usuario usuarioByIdUsuarioEnvia;
	private short ultimoMovimiento;
	private Date fechaAutoriza;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String motivoRechazo;
	private Integer numeroProveedor;
	private Short visible;
	private Short rechazado;
	private Short automatico;

	public SolicitudAutorizacion() {
	}

	public SolicitudAutorizacion(int idSolicitudAutorizacion, EstadoAutorizacion estadoAutorizacion,
			EstadoSolicitud estadoSolicitud, Solicitud solicitud, TipoCriterio tipoCriterio,
			Usuario usuarioByIdUsuarioAutoriza, Usuario usuarioByIdUsuarioEnvia, short ultimoMovimiento, short activo,
			Date creacionFecha, int creacionUsuario) {
		this.idSolicitudAutorizacion = idSolicitudAutorizacion;
		this.estadoAutorizacion = estadoAutorizacion;
		this.estadoSolicitud = estadoSolicitud;
		this.solicitud = solicitud;
		this.tipoCriterio = tipoCriterio;
		this.usuarioByIdUsuarioAutoriza = usuarioByIdUsuarioAutoriza;
		this.usuarioByIdUsuarioEnvia = usuarioByIdUsuarioEnvia;
		this.ultimoMovimiento = ultimoMovimiento;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public SolicitudAutorizacion(int idSolicitudAutorizacion, EstadoAutorizacion estadoAutorizacion,
			EstadoSolicitud estadoSolicitud, Solicitud solicitud, TipoCriterio tipoCriterio,
			Usuario usuarioByIdUsuarioAutoriza, Usuario usuarioByIdUsuarioEnvia, short ultimoMovimiento,
			Date fechaAutoriza, short activo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idSolicitudAutorizacion = idSolicitudAutorizacion;
		this.estadoAutorizacion = estadoAutorizacion;
		this.estadoSolicitud = estadoSolicitud;
		this.solicitud = solicitud;
		this.tipoCriterio = tipoCriterio;
		this.usuarioByIdUsuarioAutoriza = usuarioByIdUsuarioAutoriza;
		this.usuarioByIdUsuarioEnvia = usuarioByIdUsuarioEnvia;
		this.ultimoMovimiento = ultimoMovimiento;
		this.fechaAutoriza = fechaAutoriza;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_SOLICITUD_AUTORIZACION", unique = true, nullable = false)
	public int getIdSolicitudAutorizacion() {
		return this.idSolicitudAutorizacion;
	}

	public void setIdSolicitudAutorizacion(int idSolicitudAutorizacion) {
		this.idSolicitudAutorizacion = idSolicitudAutorizacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_ESTADO_AUTORIZACION", nullable = false)
	public EstadoAutorizacion getEstadoAutorizacion() {
		return this.estadoAutorizacion;
	}

	public void setEstadoAutorizacion(EstadoAutorizacion estadoAutorizacion) {
		this.estadoAutorizacion = estadoAutorizacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_ESTADO_SOLICITUD", nullable = false)
	public EstadoSolicitud getEstadoSolicitud() {
		return this.estadoSolicitud;
	}

	public void setEstadoSolicitud(EstadoSolicitud estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_SOLICITUD", nullable = false)
	public Solicitud getSolicitud() {
		return this.solicitud;
	}

	public void setSolicitud(Solicitud solicitud) {
		this.solicitud = solicitud;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_CRITERIO", nullable = false)
	public TipoCriterio getTipoCriterio() {
		return this.tipoCriterio;
	}

	public void setTipoCriterio(TipoCriterio tipoCriterio) {
		this.tipoCriterio = tipoCriterio;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO_AUTORIZA", nullable = false)
	public Usuario getUsuarioByIdUsuarioAutoriza() {
		return this.usuarioByIdUsuarioAutoriza;
	}

	public void setUsuarioByIdUsuarioAutoriza(Usuario usuarioByIdUsuarioAutoriza) {
		this.usuarioByIdUsuarioAutoriza = usuarioByIdUsuarioAutoriza;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO_ENVIA", nullable = false)
	public Usuario getUsuarioByIdUsuarioEnvia() {
		return this.usuarioByIdUsuarioEnvia;
	}

	public void setUsuarioByIdUsuarioEnvia(Usuario usuarioByIdUsuarioEnvia) {
		this.usuarioByIdUsuarioEnvia = usuarioByIdUsuarioEnvia;
	}

	@Column(name = "ULTIMO_MOVIMIENTO", nullable = false)
	public short getUltimoMovimiento() {
		return this.ultimoMovimiento;
	}

	public void setUltimoMovimiento(short ultimoMovimiento) {
		this.ultimoMovimiento = ultimoMovimiento;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FECHA_AUTORIZA", length = 26)
	public Date getFechaAutoriza() {
		return this.fechaAutoriza;
	}

	public void setFechaAutoriza(Date fechaAutoriza) {
		this.fechaAutoriza = fechaAutoriza;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "MOTIVO_RECHAZO", length = 500)
	public String getMotivoRechazo() {
		return this.motivoRechazo;
	}

	public void setMotivoRechazo(String motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}
	
	@Column(name = "NUMERO_PROVEEDOR")
	public Integer getNumeroProveedor() {
		return numeroProveedor;
	}

	public void setNumeroProveedor(Integer numeroProveedor) {
		this.numeroProveedor = numeroProveedor;
	}

	@Column(name = "VISIBLE")
	public Short getVisible() {
		return visible;
	}

	public void setVisible(Short visible) {
		this.visible = visible;
	}

	@Column(name = "RECHAZADO")
	public Short getRechazado() {
		return rechazado;
	}

	public void setRechazado(Short rechazado) {
		this.rechazado = rechazado;
	}

	@Column(name = "AUTOMATICO")
	public Short getAutomatico() {
		return automatico;
	}

	public void setAutomatico(Short automatico) {
		this.automatico = automatico;
	}	
	

}
