package com.lowes.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
* TipoSolicitudCriterio generated by hbm2java
*/
@Entity
@Table(name = "TIPO_SOLICITUD_CRITERIO", schema = "LWS584")
public class TipoSolicitudCriterio implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	private int idTipoSolicitudCriterio;
	private TipoCriterio tipoCriterio;
	private TipoSolicitud tipoSolicitud;
	private int orden;

	public TipoSolicitudCriterio() {
	}

	public TipoSolicitudCriterio(int idTipoSolicitudCriterio, TipoCriterio tipoCriterio, TipoSolicitud tipoSolicitud, int orden) {
		this.idTipoSolicitudCriterio = idTipoSolicitudCriterio;
		this.tipoCriterio = tipoCriterio;
		this.tipoSolicitud = tipoSolicitud;
		this.orden = orden;
	}

	@Id
	@GeneratedValue (strategy = GenerationType.AUTO)
	@Column(name = "ID_TIPO_SOLICITUD_CRITERIO", unique = true, nullable = false)
	public int getIdTipoSolicitudCriterio() {
		return this.idTipoSolicitudCriterio;
	}

	public void setIdTipoSolicitudCriterio(int idTipoSolicitudCriterio) {
		this.idTipoSolicitudCriterio = idTipoSolicitudCriterio;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_CRITERIO", nullable = false)
	public TipoCriterio getTipoCriterio() {
		return this.tipoCriterio;
	}

	public void setTipoCriterio(TipoCriterio tipoCriterio) {
		this.tipoCriterio = tipoCriterio;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_SOLICITUD", nullable = false)
	public TipoSolicitud getTipoSolicitud() {
		return this.tipoSolicitud;
	}

	public void setTipoSolicitud(TipoSolicitud tipoSolicitud) {
		this.tipoSolicitud = tipoSolicitud;
	}
	
	@Column(name = "ORDEN", nullable = false)
	public int getOrden() {
		return this.orden;
	}

	public void setOrden(int orden) {
		this.orden = orden;
	}

}
