package com.lowes.entity;

//Generated 19/01/2016 12:02:35 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* TipoFactura generated by hbm2java
*/
@Entity
@Table(name = "TIPO_FACTURA")
public class TipoFactura implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idTipoFactura;
	private String descripcion;
	private String descripcionEbs;

	public TipoFactura() {
	}

	public TipoFactura(int idTipoFactura) {
		this.idTipoFactura = idTipoFactura;
	}

	public TipoFactura(int idTipoFactura, String descripcion, String descripcionEbs) {
		this.idTipoFactura = idTipoFactura;
		this.descripcion = descripcion;
		this.descripcionEbs = descripcionEbs;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_TIPO_FACTURA", unique = true, nullable = false)
	public int getIdTipoFactura() {
		return this.idTipoFactura;
	}

	public void setIdTipoFactura(int idTipoFactura) {
		this.idTipoFactura = idTipoFactura;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 5)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}
	
	@Column(name = "DESCRIPCION_EBS", length = 20)
	public String getDescripcionEbs() {
		return this.descripcionEbs;
	}

	public void setDescripcionEbs(String descripcionEbs) {
		this.descripcionEbs = descripcionEbs;
	}

}