package com.lowes.entity;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
* TipoSolicitud generated by hbm2java
*/
@Entity
@Table(name = "TIPO_SOLICITUD")
public class TipoSolicitud implements java.io.Serializable {

	private static final long serialVersionUID = -1818877715311575364L;
	
	private int idTipoSolicitud;
	private String descripcion;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	private String colorSolicitud;
	private BigDecimal montoConfirmacionPesos;
	private BigDecimal montoConfirmacionDolares;
	
	private String descripcionInvoiceTypeEBS;
	private String prefijoInvoiceNumEBS;
	private String prefijoDescriptionEBS;	
	
	private String strMontoConfirmacionPesos;
	private String strMontoConfirmacionDolares;


	public TipoSolicitud() {
	}
	
	public TipoSolicitud(int idTipoSolicitud){
		this.idTipoSolicitud = idTipoSolicitud;
	}

	public TipoSolicitud(int idTipoSolicitud, String descripcion, short activo, Date creacionFecha,
			int creacionUsuario,String colorSolicitud) {
		this.idTipoSolicitud = idTipoSolicitud;
		this.descripcion = descripcion;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.colorSolicitud = colorSolicitud;
	}

	public TipoSolicitud(int idTipoSolicitud, String descripcion, short activo, Date creacionFecha, int creacionUsuario,
			Date modificacionFecha, Integer modificacionUsuario, String colorSolicitud,
			BigDecimal montoConfirmacionPesos, BigDecimal montoConfirmacionDolares) {
		this.idTipoSolicitud = idTipoSolicitud;
		this.descripcion = descripcion;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
		this.colorSolicitud = colorSolicitud;
		this.montoConfirmacionPesos = montoConfirmacionPesos;
		this.montoConfirmacionDolares = montoConfirmacionDolares;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_TIPO_SOLICITUD", unique = true, nullable = false)
	public int getIdTipoSolicitud() {
		return this.idTipoSolicitud;
	}

	public void setIdTipoSolicitud(int idTipoSolicitud) {
		this.idTipoSolicitud = idTipoSolicitud;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Column(name = "COLOR_SOLICITUD", length = 15)
	public String getColorSolicitud() {
		return this.colorSolicitud;
	}

	public void setColorSolicitud(String colorSolicitud) {
		this.colorSolicitud = colorSolicitud;
	}
	
	@Column(name = "MONTO_CONFIRMACION_PESOS", nullable = false, precision = 17)
	public BigDecimal getMontoConfirmacionPesos() {
		return this.montoConfirmacionPesos;
	}

	public void setMontoConfirmacionPesos(BigDecimal montoConfirmacionPesos) {
		this.montoConfirmacionPesos = montoConfirmacionPesos;
	}

	@Column(name = "MONTO_CONFIRMACION_DOLARES", nullable = false, precision = 17)
	public BigDecimal getMontoConfirmacionDolares() {
		return this.montoConfirmacionDolares;
	}

	public void setMontoConfirmacionDolares(BigDecimal montoConfirmacionDolares) {
		this.montoConfirmacionDolares = montoConfirmacionDolares;
	}
	
	@Column(name = "DESCRIPCION_INVOICE_TYPE_EBS", length = 20)
	public String getDescripcionInvoiceTypeEBS() {
		return descripcionInvoiceTypeEBS;
	}

	public void setDescripcionInvoiceTypeEBS(String descripcionInvoiceTypeEBS) {
		this.descripcionInvoiceTypeEBS = descripcionInvoiceTypeEBS;
	}

	@Column(name = "PREFIJO_INVOICE_NUM_EBS", length = 15)
	public String getPrefijoInvoiceNumEBS() {
		return prefijoInvoiceNumEBS;
	}

	public void setPrefijoInvoiceNumEBS(String prefijoInvoiceNumEBS) {
		this.prefijoInvoiceNumEBS = prefijoInvoiceNumEBS;
	}

	@Column(name = "PREFIJO_DESCRIPTION_EBS", length = 50)
	public String getPrefijoDescriptionEBS() {
		return prefijoDescriptionEBS;
	}

	public void setPrefijoDescriptionEBS(String prefijoDescriptionEBS) {
		this.prefijoDescriptionEBS = prefijoDescriptionEBS;
	}

	@Transient
	public String getStrMontoConfirmacionPesos() {
		return strMontoConfirmacionPesos;
	}

	public void setStrMontoConfirmacionPesos(String strMontoConfirmacionPesos) {
		this.strMontoConfirmacionPesos = strMontoConfirmacionPesos;
	}

	@Transient
	public String getStrMontoConfirmacionDolares() {
		return strMontoConfirmacionDolares;
	}

	public void setStrMontoConfirmacionDolares(String strMontoConfirmacionDolares) {
		this.strMontoConfirmacionDolares = strMontoConfirmacionDolares;
	}
}