package com.lowes.entity;

//Generated 18/03/2016 12:14:20 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

/**
* TipoProveedor generated by hbm2java
*/
@Entity
@Table(name = "TIPO_PROVEEDOR")
public class TipoProveedor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idTipoProveedor;
	private String descripcion;

	public TipoProveedor(int idTipoProveedor) {
		this.idTipoProveedor = idTipoProveedor;
	}
	
	public TipoProveedor() {
	}

	public TipoProveedor(int idTipoProveedor, String descripcion) {
		this.idTipoProveedor = idTipoProveedor;
		this.descripcion = descripcion;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_TIPO_PROVEEDOR", unique = true, nullable = false)
	public int getIdTipoProveedor() {
		return this.idTipoProveedor;
	}

	public void setIdTipoProveedor(int idTipoProveedor) {
		this.idTipoProveedor = idTipoProveedor;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}