package com.lowes.entity;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.LazyCollection;
import org.hibernate.annotations.LazyCollectionOption;

/**
 * UsuarioConfSolicitante generated by hbm2java
 */
@Entity
@Table(name = "USUARIO_CONFIGURACION_SOLICITANTE", schema = "LWS584")
public class UsuarioConfSolicitante implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	private int idUsuarioConfSolicitante;
	private CuentaContable cuentaContable;
	private Locacion locacion;
	private TipoSolicitud tipoSolicitud;
	private Usuario usuario;
	private short activo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	//Transients
	private int idCuentaContable;
	private int idLocacion;
	private int idTipoSolicitud;
	private int idUsuario;

	public UsuarioConfSolicitante() {
	}

	public UsuarioConfSolicitante(int idUsuarioConfSolicitante, CuentaContable cuentaContable,
			Locacion locacion, TipoSolicitud tipoSolicitud, Usuario usuario, short activo, Date creacionFecha,
			int creacionUsuario) {
		this.idUsuarioConfSolicitante = idUsuarioConfSolicitante;
		this.cuentaContable = cuentaContable;
		this.locacion = locacion;
		this.tipoSolicitud = tipoSolicitud;
		this.usuario = usuario;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public UsuarioConfSolicitante(int idUsuarioConfSolicitante, CuentaContable cuentaContable,
			Locacion locacion, TipoSolicitud tipoSolicitud, Usuario usuario, short activo, Date creacionFecha,
			int creacionUsuario, Date modificacionFecha, Integer modificacionUsuario) {
		this.idUsuarioConfSolicitante = idUsuarioConfSolicitante;
		this.cuentaContable = cuentaContable;
		this.locacion = locacion;
		this.tipoSolicitud = tipoSolicitud;
		this.usuario = usuario;
		this.activo = activo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_USUARIO_CONFIGURACION_SOLICITANTE", unique = true, nullable = false)
	public int getIdUsuarioConfSolicitante() {
		return this.idUsuarioConfSolicitante;
	}

	public void setIdUsuarioConfSolicitante(int idUsuarioConfSolicitante) {
		this.idUsuarioConfSolicitante = idUsuarioConfSolicitante;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_CUENTA_CONTABLE", nullable = false)
	public CuentaContable getCuentaContable() {
		return this.cuentaContable;
	}

	public void setCuentaContable(CuentaContable cuentaContable) {
		this.cuentaContable = cuentaContable;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_LOCACION", nullable = false)
	public Locacion getLocacion() {
		return this.locacion;
	}

	public void setLocacion(Locacion locacion) {
		this.locacion = locacion;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_TIPO_SOLICITUD", nullable = false)
	public TipoSolicitud getTipoSolicitud() {
		return this.tipoSolicitud;
	}

	public void setTipoSolicitud(TipoSolicitud tipoSolicitud) {
		this.tipoSolicitud = tipoSolicitud;
	}

	@LazyCollection(LazyCollectionOption.FALSE)
	@ManyToOne
	@JoinColumn(name = "ID_USUARIO", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}
	
	@Transient
	public int getIdCuentaContable() {
		return idCuentaContable;
	}

	public void setIdCuentaContable(int idCuentaContable) {
		this.idCuentaContable = idCuentaContable;
	}

	@Transient
	public int getIdLocacion() {
		return idLocacion;
	}

	public void setIdLocacion(int idLocacion) {
		this.idLocacion = idLocacion;
	}

	@Transient
	public int getIdTipoSolicitud() {
		return idTipoSolicitud;
	}

	public void setIdTipoSolicitud(int idTipoSolicitud) {
		this.idTipoSolicitud = idTipoSolicitud;
	}

	@Transient
	public int getIdUsuario() {
		return idUsuario;
	}

	public void setIdUsuario(int idUsuario) {
		this.idUsuario = idUsuario;
	}
	
	

}