package com.lowes.entity;

// default package
// Generated 21-abr-2016 9:54:17 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * ViajeConcepto generated by hbm2java
 */
@Entity
@Table(name = "VIAJE_CONCEPTO")
public class ViajeConcepto implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/*Id dinámico basado en descripción para la vista*/
	private String idViajeConceptoString;
	/**/
	private int idViajeConcepto;
	private String descripcion;
	private BigDecimal dolaresTarifa;
	private BigDecimal pesosTarifa;
	private short esCalculado;
	private short calculoImporteDiario;
	private short calculoDias;
	private short calculoPersonas;
	private short esOtro;
	private boolean esCalculadoB;
	private boolean calculoImporteDiarioB;
	private boolean calculoDiasB;
	private boolean calculoPersonasB;
	private boolean esOtroB;
	private short activo;
	private short esPropina;
	private short esTransporteAereo;
	private Date creacionFecha;
	private int creacionUsuario;
	private Date modificacionFecha;
	private Integer modificacionUsuario;
	
	private BigDecimal importe;

	public ViajeConcepto() {
	}
	
	public ViajeConcepto(int idViajeConcepto) {
		this.idViajeConcepto = idViajeConcepto;
	}


	public ViajeConcepto(int idViajeConcepto, String descripcion, BigDecimal dolaresTarifa, BigDecimal pesosTarifa,
			short esCalculado, short activo, short esPropina, short esTransporteAereo, Date creacionFecha, int creacionUsuario) {
		this.idViajeConcepto = idViajeConcepto;
		this.descripcion = descripcion;
		this.dolaresTarifa = dolaresTarifa;
		this.pesosTarifa = pesosTarifa;
		this.esCalculado = esCalculado;
		this.activo = activo;
		this.esPropina = esPropina;
		this.esTransporteAereo = esTransporteAereo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
	}

	public ViajeConcepto(int idViajeConcepto, String descripcion, BigDecimal dolaresTarifa, BigDecimal pesosTarifa,
			short esCalculado, short calculoImporteDiario, short calculoDias, short calculoPersonas, short esOtro,
			short activo, short esPropina, short esTransporteAereo, Date creacionFecha, int creacionUsuario, Date modificacionFecha,
			Integer modificacionUsuario) {
		this.idViajeConcepto = idViajeConcepto;
		this.descripcion = descripcion;
		this.dolaresTarifa = dolaresTarifa;
		this.pesosTarifa = pesosTarifa;
		this.esCalculado = esCalculado;
		this.calculoImporteDiario = calculoImporteDiario;
		this.calculoDias = calculoDias;
		this.calculoPersonas = calculoPersonas;
		this.esOtro = esOtro;
		this.activo = activo;
		this.esPropina = esPropina;
		this.esTransporteAereo = esTransporteAereo;
		this.creacionFecha = creacionFecha;
		this.creacionUsuario = creacionUsuario;
		this.modificacionFecha = modificacionFecha;
		this.modificacionUsuario = modificacionUsuario;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "ID_VIAJE_CONCEPTO", unique = true, nullable = false)
	public int getIdViajeConcepto() {
		return this.idViajeConcepto;
	}

	public void setIdViajeConcepto(int idViajeConcepto) {
		this.idViajeConcepto = idViajeConcepto;
	}

	@Column(name = "DESCRIPCION", nullable = false, length = 100)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "DOLARES_TARIFA", nullable = false, precision = 17)
	public BigDecimal getDolaresTarifa() {
		return this.dolaresTarifa;
	}

	public void setDolaresTarifa(BigDecimal dolaresTarifa) {
		this.dolaresTarifa = dolaresTarifa;
	}

	@Column(name = "PESOS_TARIFA", nullable = false, precision = 17)
	public BigDecimal getPesosTarifa() {
		return this.pesosTarifa;
	}

	public void setPesosTarifa(BigDecimal pesosTarifa) {
		this.pesosTarifa = pesosTarifa;
	}

	@Column(name = "ES_CALCULADO", nullable = false)
	public short getEsCalculado() {
		return this.esCalculado;
	}

	public void setEsCalculado(short esCalculado) {
		this.esCalculado = esCalculado;
	}

	@Column(name = "CALCULO_IMPORTE_DIARIO")
	public short getCalculoImporteDiario() {
		return this.calculoImporteDiario;
	}

	public void setCalculoImporteDiario(short calculoImporteDiario) {
		this.calculoImporteDiario = calculoImporteDiario;
	}

	@Column(name = "CALCULO_DIAS")
	public short getCalculoDias() {
		return this.calculoDias;
	}

	public void setCalculoDias(short calculoDias) {
		this.calculoDias = calculoDias;
	}

	@Column(name = "CALCULO_PERSONAS")
	public short getCalculoPersonas() {
		return this.calculoPersonas;
	}

	public void setCalculoPersonas(short calculoPersonas) {
		this.calculoPersonas = calculoPersonas;
	}

	@Column(name = "ES_OTRO")
	public short getEsOtro() {
		return this.esOtro;
	}

	public void setEsOtro(short esOtro) {
		this.esOtro = esOtro;
	}

	@Column(name = "ACTIVO", nullable = false)
	public short getActivo() {
		return this.activo;
	}

	public void setActivo(short activo) {
		this.activo = activo;
	}
	
	@Column(name = "ES_PROPINA")
	public short getEsPropina() {
		return this.esPropina;
	}

	public void setEsPropina(short esPropina) {
		this.esPropina = esPropina;
	}
	
	@Column(name = "ES_TRANSPORTE_AEREO")
	public short getEsTransporteAereo() {
		return this.esTransporteAereo;
	}

	public void setEsTransporteAereo(short esTransporteAereo) {
		this.esTransporteAereo = esTransporteAereo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CREACION_USUARIO", nullable = false)
	public int getCreacionUsuario() {
		return this.creacionUsuario;
	}

	public void setCreacionUsuario(int creacionUsuario) {
		this.creacionUsuario = creacionUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFICACION_FECHA", length = 26)
	public Date getModificacionFecha() {
		return this.modificacionFecha;
	}

	public void setModificacionFecha(Date modificacionFecha) {
		this.modificacionFecha = modificacionFecha;
	}

	@Column(name = "MODIFICACION_USUARIO")
	public Integer getModificacionUsuario() {
		return this.modificacionUsuario;
	}

	public void setModificacionUsuario(Integer modificacionUsuario) {
		this.modificacionUsuario = modificacionUsuario;
	}

	@Transient
	public boolean getEsCalculadoB() {
		return esCalculadoB;
	}

	public void setEsCalculadoB(boolean esCalculadoB) {
		this.esCalculadoB = esCalculadoB;
	}

	@Transient
	public boolean getCalculoImporteDiarioB() {
		return calculoImporteDiarioB;
	}

	public void setCalculoImporteDiarioB(boolean calculoImporteDiarioB) {
		this.calculoImporteDiarioB = calculoImporteDiarioB;
	}

	@Transient
	public boolean getCalculoDiasB() {
		return calculoDiasB;
	}

	public void setCalculoDiasB(boolean calculoDiasB) {
		this.calculoDiasB = calculoDiasB;
	}

	@Transient
	public boolean getCalculoPersonasB() {
		return calculoPersonasB;
	}

	public void setCalculoPersonasB(boolean calculoPersonasB) {
		this.calculoPersonasB = calculoPersonasB;
	}
	
	@Transient
	public boolean getEsOtroB() {
		return esOtroB;
	}

	public void setEsOtroB(boolean esOtroB) {
		this.esOtroB = esOtroB;
	}
	
	@Transient
	public BigDecimal getImporte() {
		return importe;
	}

	public void setImporte(BigDecimal importe) {
		this.importe = importe;
	}

	@Transient
	public String getIdViajeConceptoString() {
		return idViajeConceptoString;
	}

	public void setIdViajeConceptoString(String idViajeConceptoString) {
		this.idViajeConceptoString = idViajeConceptoString;
	}

}
