package com.lowes.entity;
// Generated 25/01/2016 08:06:09 PM by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * VwSolicitudResumenAutorizacion generated by hbm2java
 */
@Entity
@Table(name = "VW_SOLICITUD_RESUMEN_AUTORIZACION", schema = "LWS584")
public class VwSolicitudResumenAutorizacion implements java.io.Serializable {

private static final long serialVersionUID = 1L;

	private long idVwSolicitudResumen;
	private int idSolicitud;
	private Integer idUsuarioSolicita;
	private String usuarioSolicita;
	private int idTipoSolicitud;
	private String tipoSolicitud;
	private int idEstadoSolicitud;
	private String estadoSolicitud;
	private Date creacionFecha;
	private String conceptoGasto;
	private String motivoRechazo;
	private int idEstadoAutorizacion;
	private String estadoAutorizacion;
	private Integer idProveedor;
	private String proveedor;
	private String factura;
	private Date fechaFactura;
	private BigDecimal subtotal;
	private int idMoneda;
	private String moneda;
	private int idUsuarioAutoriza;
	private Integer idCompania;
	private String compania;
	private Date ultimaFechaAutoriza;
	private String colorSolicitud;
	private BigDecimal montoTotal;
	private Integer id_usuarioAsesor;
	private String  usuarioAsesor;
	private Integer numeroProveedor;
	private Integer numeroProveedorProveedor;
	private Integer numeroProveedorProveedorAsesor;
	private Integer tipoFactura;
	private Integer idMonedaSolicitud;
	private String  monedaSolicitud;

	
	
	//Transient
	private boolean autorizar;
	private boolean rechazar;

	public VwSolicitudResumenAutorizacion() {
	}

	public VwSolicitudResumenAutorizacion(long idVwSolicitudResumen, int idSolicitud, String usuarioSolicita,
			int idTipoSolicitud, String tipoSolicitud, int idEstadoSolicitud, String estadoSolicitud,
			Date creacionFecha, int idEstadoAutorizacion, String estadoAutorizacion, String factura, int idMoneda,
			int idUsuarioAutoriza, String colorSolicitud) {
		this.idVwSolicitudResumen = idVwSolicitudResumen;
		this.idSolicitud = idSolicitud;
		this.usuarioSolicita = usuarioSolicita;
		this.idTipoSolicitud = idTipoSolicitud;
		this.tipoSolicitud = tipoSolicitud;
		this.idEstadoSolicitud = idEstadoSolicitud;
		this.estadoSolicitud = estadoSolicitud;
		this.creacionFecha = creacionFecha;
		this.idEstadoAutorizacion = idEstadoAutorizacion;
		this.estadoAutorizacion = estadoAutorizacion;
		this.factura = factura;
		this.idMoneda = idMoneda;
		this.idUsuarioAutoriza = idUsuarioAutoriza;
		this.colorSolicitud = colorSolicitud;
	}

	public VwSolicitudResumenAutorizacion(long idVwSolicitudResumen, int idSolicitud, Integer idUsuarioSolicita,
			String usuarioSolicita, int idTipoSolicitud, String tipoSolicitud, int idEstadoSolicitud,
			String estadoSolicitud, Date creacionFecha, String conceptoGasto, String motivoRechazo, int idEstadoAutorizacion,
			String estadoAutorizacion, Integer idProveedor, String proveedor, String factura, Date fechaFactura,
			BigDecimal subtotal, int idMoneda, String moneda, int idUsuarioAutoriza, Integer idCompania,
			String compania, Date ultimaFechaAutoriza, String colorSolicitud) {
		this.idVwSolicitudResumen = idVwSolicitudResumen;
		this.idSolicitud = idSolicitud;
		this.idUsuarioSolicita = idUsuarioSolicita;
		this.usuarioSolicita = usuarioSolicita;
		this.idTipoSolicitud = idTipoSolicitud;
		this.tipoSolicitud = tipoSolicitud;
		this.idEstadoSolicitud = idEstadoSolicitud;
		this.estadoSolicitud = estadoSolicitud;
		this.creacionFecha = creacionFecha;
		this.conceptoGasto = conceptoGasto;
		this.motivoRechazo = motivoRechazo;
		this.idEstadoAutorizacion = idEstadoAutorizacion;
		this.estadoAutorizacion = estadoAutorizacion;
		this.idProveedor = idProveedor;
		this.proveedor = proveedor;
		this.factura = factura;
		this.fechaFactura = fechaFactura;
		this.subtotal = subtotal;
		this.idMoneda = idMoneda;
		this.moneda = moneda;
		this.idUsuarioAutoriza = idUsuarioAutoriza;
		this.idCompania = idCompania;
		this.compania = compania;
		this.ultimaFechaAutoriza = ultimaFechaAutoriza;
		this.colorSolicitud = colorSolicitud;
	}
	
	@Id
	@Column(name = "ID_VW_SOLICITUD_RESUMEN", nullable = false)
	public long getIdVwSolicitudResumen() {
		return this.idVwSolicitudResumen;
	}

	public void setIdVwSolicitudResumen(long idVwSolicitudResumen) {
		this.idVwSolicitudResumen = idVwSolicitudResumen;
	}

	@Column(name = "ID_SOLICITUD", nullable = false)
	public int getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(int idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	@Column(name = "ID_USUARIO_SOLICITA")
	public Integer getIdUsuarioSolicita() {
		return this.idUsuarioSolicita;
	}

	public void setIdUsuarioSolicita(Integer idUsuarioSolicita) {
		this.idUsuarioSolicita = idUsuarioSolicita;
	}

	@Column(name = "USUARIO_SOLICITA", nullable = false, length = 102)
	public String getUsuarioSolicita() {
		return this.usuarioSolicita;
	}

	public void setUsuarioSolicita(String usuarioSolicita) {
		this.usuarioSolicita = usuarioSolicita;
	}

	@Column(name = "ID_TIPO_SOLICITUD", nullable = false)
	public int getIdTipoSolicitud() {
		return this.idTipoSolicitud;
	}

	public void setIdTipoSolicitud(int idTipoSolicitud) {
		this.idTipoSolicitud = idTipoSolicitud;
	}

	@Column(name = "TIPO_SOLICITUD", nullable = false, length = 100)
	public String getTipoSolicitud() {
		return this.tipoSolicitud;
	}

	public void setTipoSolicitud(String tipoSolicitud) {
		this.tipoSolicitud = tipoSolicitud;
    }
	
	@Column(name = "COLOR_SOLICITUD", length = 15)
 	public String getColorSolicitud() {
		return colorSolicitud;
	}

	public void setColorSolicitud(String colorSolicitud) {
		this.colorSolicitud = colorSolicitud;
	}

	@Column(name = "ID_ESTADO_SOLICITUD", nullable = false)
	public int getIdEstadoSolicitud() {
		return this.idEstadoSolicitud;
	}

	public void setIdEstadoSolicitud(int idEstadoSolicitud) {
		this.idEstadoSolicitud = idEstadoSolicitud;
	}

	@Column(name = "ESTADO_SOLICITUD", nullable = false, length = 100)
	public String getEstadoSolicitud() {
		return this.estadoSolicitud;
	}

	public void setEstadoSolicitud(String estadoSolicitud) {
		this.estadoSolicitud = estadoSolicitud;
	}

	@Column(name = "CREACION_FECHA", nullable = false, length = 26)
	public Date getCreacionFecha() {
		return this.creacionFecha;
	}

	public void setCreacionFecha(Date creacionFecha) {
		this.creacionFecha = creacionFecha;
	}

	@Column(name = "CONCEPTO_GASTO", length = 500)
	public String getConceptoGasto() {
		return this.conceptoGasto;
	}

	public void setConceptoGasto(String conceptoGasto) {
		this.conceptoGasto = conceptoGasto;
	}

	@Column(name = "MOTIVO_RECHAZO", length = 500)
	public String getMotivoRechazo() {
		return this.motivoRechazo;
	}

	public void setMotivoRechazo(String motivoRechazo) {
		this.motivoRechazo = motivoRechazo;
	}

	@Column(name = "ID_ESTADO_AUTORIZACION", nullable = false)
	public int getIdEstadoAutorizacion() {
		return this.idEstadoAutorizacion;
	}

	public void setIdEstadoAutorizacion(int idEstadoAutorizacion) {
		this.idEstadoAutorizacion = idEstadoAutorizacion;
	}

	@Column(name = "ESTADO_AUTORIZACION", nullable = false, length = 100)
	public String getEstadoAutorizacion() {
		return this.estadoAutorizacion;
	}

	public void setestadoAutorizacion(String estadoAutorizacion) {
		this.estadoAutorizacion = estadoAutorizacion;
	}

	@Column(name = "ID_PROVEEDOR")
	public Integer getIdProveedor() {
		return this.idProveedor;
	}

	public void setIdProveedor(Integer idProveedor) {
		this.idProveedor = idProveedor;
	}

	@Column(name = "PROVEEDOR", length = 100)
	public String getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "FACTURA", nullable = false, length = 10)
	public String getFactura() {
		return this.factura;
	}

	public void setFactura(String factura) {
		this.factura = factura;
	}

	@Column(name = "FECHA_FACTURA", length = 10)
	public Date getFechaFactura() {
		return this.fechaFactura;
	}

	public void setFechaFactura(Date fechaFactura) {
		this.fechaFactura = fechaFactura;
	}

	@Column(name = "SUBTOTAL", precision = 17)
	public BigDecimal getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(BigDecimal subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "ID_MONEDA", nullable = false)
	public int getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(int idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "MONEDA", length = 100)
	public String getMoneda() {
		return this.moneda;
	}

	public void setMoneda(String moneda) {
		this.moneda = moneda;
	}

	@Column(name = "ID_USUARIO_AUTORIZA", nullable = false)
	public int getIdUsuarioAutoriza() {
		return this.idUsuarioAutoriza;
	}

	public void setIdUsuarioAutoriza(int idUsuarioAutoriza) {
		this.idUsuarioAutoriza = idUsuarioAutoriza;
	}

	@Column(name = "ID_COMPANIA")
	public Integer getIdCompania() {
		return this.idCompania;
	}

	public void setIdCompania(Integer idCompania) {
		this.idCompania = idCompania;
	}

	@Column(name = "COMPANIA", length = 100)
	public String getCompania() {
		return this.compania;
	}

	public void setCompania(String compania) {
		this.compania = compania;
	}

	@Column(name = "ULTIMA_FECHA_AUTORIZA", length = 26)
	public Date getUltimaFechaAutoriza() {
		return this.ultimaFechaAutoriza;
	}

	public void setUltimaFechaAutoriza(Date ultimaFechaAutoriza) {
		this.ultimaFechaAutoriza = ultimaFechaAutoriza;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwSolicitudResumenAutorizacion))
			return false;
		VwSolicitudResumenAutorizacion castOther = (VwSolicitudResumenAutorizacion) other;

		return (this.getIdVwSolicitudResumen() == castOther.getIdVwSolicitudResumen())
				&& (this.getIdSolicitud() == castOther.getIdSolicitud())
				&& ((this.getIdUsuarioSolicita() == castOther.getIdUsuarioSolicita())
						|| (this.getIdUsuarioSolicita() != null && castOther.getIdUsuarioSolicita() != null
								&& this.getIdUsuarioSolicita().equals(castOther.getIdUsuarioSolicita())))
				&& ((this.getUsuarioSolicita() == castOther.getUsuarioSolicita())
						|| (this.getUsuarioSolicita() != null && castOther.getUsuarioSolicita() != null
								&& this.getUsuarioSolicita().equals(castOther.getUsuarioSolicita())))
				&& (this.getIdTipoSolicitud() == castOther.getIdTipoSolicitud())
				&& ((this.getTipoSolicitud() == castOther.getTipoSolicitud())
						|| (this.getTipoSolicitud() != null && castOther.getTipoSolicitud() != null
								&& this.getTipoSolicitud().equals(castOther.getTipoSolicitud())))
				&& (this.getIdEstadoSolicitud() == castOther.getIdEstadoSolicitud())
				&& ((this.getEstadoSolicitud() == castOther.getEstadoSolicitud())
						|| (this.getEstadoSolicitud() != null && castOther.getEstadoSolicitud() != null
								&& this.getEstadoSolicitud().equals(castOther.getEstadoSolicitud())))
				&& ((this.getCreacionFecha() == castOther.getCreacionFecha())
						|| (this.getCreacionFecha() != null && castOther.getCreacionFecha() != null
								&& this.getCreacionFecha().equals(castOther.getCreacionFecha())))
				&& ((this.getConceptoGasto() == castOther.getConceptoGasto())
						|| (this.getConceptoGasto() != null && castOther.getConceptoGasto() != null
								&& this.getConceptoGasto().equals(castOther.getConceptoGasto())))
				&& ((this.getMotivoRechazo() == castOther.getMotivoRechazo())
						|| (this.getMotivoRechazo() != null && castOther.getMotivoRechazo() != null
								&& this.getMotivoRechazo().equals(castOther.getMotivoRechazo())))
				&& (this.getIdEstadoAutorizacion() == castOther.getIdEstadoAutorizacion())
				&& ((this.getEstadoAutorizacion() == castOther.getEstadoAutorizacion())
						|| (this.getEstadoAutorizacion() != null && castOther.getEstadoAutorizacion() != null
								&& this.getEstadoAutorizacion().equals(castOther.getEstadoAutorizacion())))
				&& ((this.getIdProveedor() == castOther.getIdProveedor())
						|| (this.getIdProveedor() != null && castOther.getIdProveedor() != null
								&& this.getIdProveedor().equals(castOther.getIdProveedor())))
				&& ((this.getProveedor() == castOther.getProveedor()) || (this.getProveedor() != null
						&& castOther.getProveedor() != null && this.getProveedor().equals(castOther.getProveedor())))
				&& ((this.getFactura() == castOther.getFactura()) || (this.getFactura() != null
						&& castOther.getFactura() != null && this.getFactura().equals(castOther.getFactura())))
				&& ((this.getFechaFactura() == castOther.getFechaFactura())
						|| (this.getFechaFactura() != null && castOther.getFechaFactura() != null
								&& this.getFechaFactura().equals(castOther.getFechaFactura())))
				&& ((this.getSubtotal() == castOther.getSubtotal()) || (this.getSubtotal() != null
						&& castOther.getSubtotal() != null && this.getSubtotal().equals(castOther.getSubtotal())))
				&& (this.getIdMoneda() == castOther.getIdMoneda())
				&& ((this.getMoneda() == castOther.getMoneda()) || (this.getMoneda() != null
						&& castOther.getMoneda() != null && this.getMoneda().equals(castOther.getMoneda())))
				&& (this.getIdUsuarioAutoriza() == castOther.getIdUsuarioAutoriza())
				&& ((this.getIdCompania() == castOther.getIdCompania()) || (this.getIdCompania() != null
						&& castOther.getIdCompania() != null && this.getIdCompania().equals(castOther.getIdCompania())))
				&& ((this.getCompania() == castOther.getCompania()) || (this.getCompania() != null
						&& castOther.getCompania() != null && this.getCompania().equals(castOther.getCompania())))
				&& ((this.getUltimaFechaAutoriza() == castOther.getUltimaFechaAutoriza())
						|| (this.getUltimaFechaAutoriza() != null && castOther.getUltimaFechaAutoriza() != null
								&& this.getUltimaFechaAutoriza().equals(castOther.getUltimaFechaAutoriza())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIdVwSolicitudResumen();
		result = 37 * result + this.getIdSolicitud();
		result = 37 * result + (getIdUsuarioSolicita() == null ? 0 : this.getIdUsuarioSolicita().hashCode());
		result = 37 * result + (getUsuarioSolicita() == null ? 0 : this.getUsuarioSolicita().hashCode());
		result = 37 * result + this.getIdTipoSolicitud();
		result = 37 * result + (getTipoSolicitud() == null ? 0 : this.getTipoSolicitud().hashCode());
		result = 37 * result + this.getIdEstadoSolicitud();
		result = 37 * result + (getEstadoSolicitud() == null ? 0 : this.getEstadoSolicitud().hashCode());
		result = 37 * result + (getCreacionFecha() == null ? 0 : this.getCreacionFecha().hashCode());
		result = 37 * result + (getConceptoGasto() == null ? 0 : this.getConceptoGasto().hashCode());
		result = 37 * result + (getMotivoRechazo() == null ? 0 : this.getMotivoRechazo().hashCode());
		result = 37 * result + this.getIdEstadoAutorizacion();
		result = 37 * result + (getEstadoAutorizacion() == null ? 0 : this.getEstadoAutorizacion().hashCode());
		result = 37 * result + (getIdProveedor() == null ? 0 : this.getIdProveedor().hashCode());
		result = 37 * result + (getProveedor() == null ? 0 : this.getProveedor().hashCode());
		result = 37 * result + (getFactura() == null ? 0 : this.getFactura().hashCode());
		result = 37 * result + (getFechaFactura() == null ? 0 : this.getFechaFactura().hashCode());
		result = 37 * result + (getSubtotal() == null ? 0 : this.getSubtotal().hashCode());
		result = 37 * result + this.getIdMoneda();
		result = 37 * result + (getMoneda() == null ? 0 : this.getMoneda().hashCode());
		result = 37 * result + this.getIdUsuarioAutoriza();
		result = 37 * result + (getIdCompania() == null ? 0 : this.getIdCompania().hashCode());
		result = 37 * result + (getCompania() == null ? 0 : this.getCompania().hashCode());
		result = 37 * result + (getUltimaFechaAutoriza() == null ? 0 : this.getUltimaFechaAutoriza().hashCode());
		return result;
	}
	
	@Transient
	public boolean isAutorizar() {
		return autorizar;
	}

	public void setAutorizar(boolean autorizar) {
		this.autorizar = autorizar;
	}
	
	@Transient
	public boolean isRechazar() {
		return rechazar;
	}

	public void setRechazar(boolean rechazar) {
		this.rechazar = rechazar;
	}
	
	@Column(name = "MONTO_TOTAL", precision = 17)
	public BigDecimal getMontoTotal() {
		return montoTotal;
	}
	
	public void setMontoTotal(BigDecimal montoTotal) {
		this.montoTotal = montoTotal;
	}
	
	@Column(name = "ID_USUARIO_ASESOR")
	public Integer getId_usuarioAsesor() {
		return id_usuarioAsesor;
	}

	public void setId_usuarioAsesor(Integer id_usuarioAsesor) {
		this.id_usuarioAsesor = id_usuarioAsesor;
	}
	
	@Column(name = "USUARIO_ASESOR", length = 102)
	public String getUsuarioAsesor() {
		return usuarioAsesor;
	}
	
	public void setUsuarioAsesor(String usuarioAsesor) {
		this.usuarioAsesor = usuarioAsesor;
	}
	
	@Column(name = "NUMERO_PROVEEDOR")
	public Integer getNumeroProveedor() {
		return numeroProveedor;
	}

	public void setNumeroProveedor(Integer numeroProveedor) {
		this.numeroProveedor = numeroProveedor;
	}

	@Column(name = "NUMERO_PROVEEDOR_PROVEEDOR")
	public Integer getNumeroProveedorProveedor() {
		return numeroProveedorProveedor;
	}

	public void setNumeroProveedorProveedor(Integer numeroProveedorProveedor) {
		this.numeroProveedorProveedor = numeroProveedorProveedor;
	}
	
	@Column(name = "NUMERO_PROVEEDOR_ASESOR")
	public Integer getNumeroProveedorProveedorAsesor() {
		return numeroProveedorProveedorAsesor;
	}

	public void setNumeroProveedorProveedorAsesor(Integer numeroProveedorProveedorAsesor) {
		this.numeroProveedorProveedorAsesor = numeroProveedorProveedorAsesor;
	}
	
	@Column(name = "TIPO_FACTURA")
	public Integer getTipoFactura() {
		return tipoFactura;
	}

	public void setTipoFactura(Integer tipoFactura) {
		this.tipoFactura = tipoFactura;
	}
	
	@Column(name = "ID_MONEDA_SOLICITUD")
	public Integer getIdMonedaSolicitud() {
		return idMonedaSolicitud;
	}

	public void setIdMonedaSolicitud(Integer idMonedaSolicitud) {
		this.idMonedaSolicitud = idMonedaSolicitud;
	}
	
	@Column(name = "MONEDA_SOLICITUD")
	public String getMonedaSolicitud() {
		return monedaSolicitud;
	}

	public void setMonedaSolicitud(String monedaSolicitud) {
		this.monedaSolicitud = monedaSolicitud;
	}
	
}
